### ISSUE TITLE
使用images的findImage方法找图时opencv报错

### ISSUE THREAD

**Issue by LuoJian-RJ** [kkevsekk1/AutoX#1027]
1. Autox.js 版本：6.5.8
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 12
4. Android 机型：vivo
5. Android 系统类别：MIUI
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：使用images的findImage方法找图时opencv报错
8. 报错日志（可选）：
9. 屏幕截图（可选）：
![Uploading 微信图片_20240630154525.png…]()

java.lang.UnsatisfiedlinkError: No implementation found for long org.opencv.core.Mat.n Mat() (tried Java org opencv core Mat n 1Matand Java org opencv core Matn1Mat)
at org.opencv.core.Mat.n Mat(Native Method)at org.opencv.core.Mat.<init>(Mat.java:23)
at com.stardust.autojs.core.opencv.Mat.<init>(Mat.java:37)
at com.stardust.autojs.core.image.ImageWrapper.getMat(ImageWrapper.java:104)at com.stardust.autojs.runtime.api.Images.matchTemplate(Images.kt:226)
at java.lang.reflect.Method.invoke(Native Method)
at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:206)at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:211)at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1879)at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:1061)at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:90)at org.mozilla.javascriptFunction.call(ArrowFunction.java:43)ScriptRuntime.apply0rCall(ScriptRuntime.iava:2766)at org.mozilla.javascrat org.mozilla.javascrition.execIdcall(BaseFunction.iava:327)call(IdFunction0bject.java:100)at org.mozilla.iavascriptTCFUnat org.mozilla.javascriptinterpretLoop(Interpreter.iava:1879at org.mozilla.javascrInterpreter.interpret(Interpreter.iava:1061)at org.mozilla.javasccall(InterpretedFunction.java:90)lnteroretedFunctionat org.mozilla.javArrowFunction.call(ArrowFunction.iava:43)at org.mozilla.javInterpreter.interpretLoop(Interpreter.iava:1879)at org.mozillaipt.Interpreter.interpret(Interpreter.java:1061)at org.mozillacript.InterpretedFunction.call(InterpretedFunction.java:90)org.mozillajavascript.ContextFactory.doTopCall(ContextFactory.java:380)org.mozillajavascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3869)javascript.InterpretedFunction.call(InterpretedFunction.java:88)org.mozi1javascript.ArrowFunction.call(ArrowFunction.java:43)at org.moziljavascript.InterfaceAdapter.invokeImpl(InterfaceAdapter.java:171)at org.mozillat org.mozilla.javascript.VMBridge custom$InterfaceAdapterWrapper.invokeImpl(VMBridge custom.java:151)at org.mozilla.javascript.VMBridge_custom$InterfaceAdapterWrapper.lambda$invoke$0$org-mozilla-javascript-VMBridge custom$InterfaceAdapterWrapper(VMBridge custom.java:133)at org .mozilla.javascript.MBridge_custom$InterfaceAdapterWrapper$$ExternalSyntheticLambda0.run(Unknown Source: 13)at org.mozilla.javascript.VMBridge custom$InterfaceAdapterWrapper.call(VMBridge custom.java:142)

**Comment by duandaun123** [comment]
我也遇到这个问题了..

**Comment by meiyb** [comment]
你们升级版本有这个问题吗

**Comment by javasopp** [comment]
我也遇到了这个问题。一样的，好像并没有解决，我在vscode中，使用调试模式运行就不会出现。
