### ISSUE TITLE
 Android14 打开USB调试 按钮 闪退 报错如下

### ISSUE THREAD

**Issue by Liberations** [kkevsekk1/AutoX#1037]
1. Autox.js 版本：6.6.2
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 14
4. Android 机型：vivo iqoo11
5. Android 系统类别：OriginOs
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：
编译到手机点 打开USB调试 按钮 闪退 报错如下
9. 报错日志（可选）：
` E  FATAL EXCEPTION: main
                                                                                                    Process: org.autojs.autoxjs, PID: 7296
                                                                                                    java.lang.NoSuchMethodError: No virtual method getModule()Ljava/lang/Module; in class Ljava/lang/Class; or its super classes (declaration of 'java.lang.Class' appears in /apex/com.android.art/javalib/core-oj.jar)
                                                                                                    	at ch.qos.logback.core.util.EnvUtil.logbackVersionByModule(EnvUtil.java:56)
                                                                                                    	at ch.qos.logback.core.util.EnvUtil.logbackVersion(EnvUtil.java:36)
                                                                                                    	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:75)
                                                                                                    	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:66)
                                                                                                    	at ch.qos.logback.classic.spi.LogbackServiceProvider.initializeLoggerContext(LogbackServiceProvider.java:52)
                                                                                                    	at ch.qos.logback.classic.spi.LogbackServiceProvider.initialize(LogbackServiceProvider.java:41)
                                                                                                    	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:196)
                                                                                                    	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:183)
                                                                                                    	at org.slf4j.LoggerFactory.getProvider(LoggerFactory.java:486)
                                                                                                    	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:472)
                                                                                                    	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:421)
                                                                                                    	at io.ktor.server.engine.ApplicationEngineEnvironmentBuilder.<init>(ApplicationEngineEnvironmentJvm.kt:36)
                                                                                                    	at io.ktor.server.engine.ApplicationEngineEnvironmentKt.applicationEngineEnvironment(ApplicationEngineEnvironment.kt:48)
                                                                                                    	at io.ktor.server.engine.EmbeddedServerKt.embeddedServer(EmbeddedServer.kt:92)
                                                                                                    	at io.ktor.server.engine.EmbeddedServerKt.embeddedServer(EmbeddedServer.kt:65)
                                                                                                    	at io.ktor.server.engine.EmbeddedServerKt.embeddedServer(EmbeddedServer.kt:40)
                                                                                                    	at io.ktor.server.engine.EmbeddedServerKt.embeddedServer$default(EmbeddedServer.kt:32)
                                                                                                    	at org.autojs.autojs.devplugin.WebSocketServer.listen(KtorWebSocket.kt:40)
                                                                                                    	at org.autojs.autojs.devplugin.DevPlugin$startUSBDebug$2.invokeSuspend(DevPlugin.kt:86)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
                                                                                                    	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:111)
                                                                                                    	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:811)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:715)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:702)
                                                                                                    	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@89ea4b7, androidx.compose.runtime.BroadcastFrameClock@e461424, StandaloneCoroutine{Cancelling}@5d1bb8d, AndroidUiDispatcher@d800142]
---------------------------- PROCESS ENDED (7296) for package org.autojs.autoxjs ----------------------------
2024-07-03 17:24:43.766  7296-7296  Process                 org.autojs.autoxjs                   I  Sending signal. PID: 7296 SIG: 9`
10. 屏幕截图（可选）：

**Comment by Liberations** [comment]
跟这个相似 https://youtrack.jetbrains.com/issue/KTOR-5227

**Comment by ilhxasll** [comment]
我也是，点开usb调试就闪退了

**Comment by ilhxasll** [comment]
Autox.js 版本：6.6.2
Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
Android 版本：Android 10
Android 机型：荣耀v20
Android 系统类别：MagicOs
VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：

**Comment by Liberations** [comment]
应该是用的库不对 不支持android 的  请切换成这个[logback-android](https://github.com/tony19/logback-android)

**Comment by ilhxasll** [comment]
我下的apk报错了，不是编译好的
