### ISSUE TITLE
编辑器错误，继续加油，等待修复版本

### ISSUE THREAD

**Issue by NOWorEVER** [kkevsekk1/AutoX#1046]
新版本是无法读取为文件或文件夹

旧版本编辑器是点击后闪退
设备信息: 
App version: 6.6.4
App version code: 664
Android build version: V816.0.24.5.13.DEV
Android release version: 14
Android SDK version: 34
Android build ID: UKQ1.231003.002 release-keys
Device brand: Xiaomi
Device manufacturer: Xiaomi
Device name: thor
Device model: 2203121C
Device product name: thor
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]

错误信息:
android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ActivityManagerService.registerReceiverWithFeature(Unknown Source:617)
	at android.app.IActivityManager$Stub.onTransact$registerReceiverWithFeature$(Unknown Source:70)
	at android.app.IActivityManager$Stub.onTransact(Unknown Source:4574)
	at com.android.server.am.ActivityManagerService.onTransact(Unknown Source:136)
	at android.os.Binder.execTransactInternal(Unknown Source:94)

java.lang.SecurityException:org.autojs.autoxjs.v6: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
android.os.Parcel.createExceptionOrNull(Unknown Source:7)
......
Caused by:
android.os.RemoteException:Remote stack trace:
	at com.android.server.am.ActivityManagerService.registerReceiverWithFeature(Unknown Source:617)
	at android.app.IActivityManager$Stub.onTransact$registerReceiverWithFeature$(Unknown Source:70)
	at android.app.IActivityManager$Stub.onTransact(Unknown Source:4574)
	at com.android.server.am.ActivityManagerService.onTransact(Unknown Source:136)
	at android.os.Binder.execTransactInternal(Unknown Source:94)

**Comment by kkevsekk1** [comment]
新版的没搞对存储权限



发送自我的盖乐世



-------- 原始信息 --------
发件人： NOWorEVER ***@***.***>
日期: 2024/7/8 09:36 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： Subscribed ***@***.***>
主题： [kkevsekk1/AutoX] 编辑器错误，继续加油，等待修复版本 (Issue #1046)


新版本是无法读取为文件或文件夹

旧版本编辑器是点击后闪退
设备信息:
App version: 6.6.4
App version code: 664
Android build version: V816.0.24.5.13.DEV
Android release version: 14
Android SDK version: 34
Android build ID: UKQ1.231003.002 release-keys
Device brand: Xiaomi
Device manufacturer: Xiaomi
Device name: thor
Device model: 2203121C
Device product name: thor
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]

错误信息:
android.os.RemoteException: Remote stack trace:
at com.android.server.am.ActivityManagerService.registerReceiverWithFeature(Unknown Source:617)
at android.app.IActivityManager$Stub.onTransact$registerReceiverWithFeature$(Unknown Source:70)
at android.app.IActivityManager$Stub.onTransact(Unknown Source:4574)
at com.android.server.am.ActivityManagerService.onTransact(Unknown Source:136)
at android.os.Binder.execTransactInternal(Unknown Source:94)

java.lang.SecurityException:org.autojs.autoxjs.v6: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
android.os.Parcel.createExceptionOrNull(Unknown Source:7)
......
Caused by:
android.os.RemoteException:Remote stack trace:
at com.android.server.am.ActivityManagerService.registerReceiverWithFeature(Unknown Source:617)
at android.app.IActivityManager$Stub.onTransact$registerReceiverWithFeature$(Unknown Source:70)
at android.app.IActivityManager$Stub.onTransact(Unknown Source:4574)
at com.android.server.am.ActivityManagerService.onTransact(Unknown Source:136)
at android.os.Binder.execTransactInternal(Unknown Source:94)

―

**Comment by atlasfish** [comment]
是的，我在6.6.4版本遇到了同样的问题，这迫使我退回到6.5.9版本，希望能得到解决
