### ISSUE TITLE
无法运行录制脚本，无法生成布局分析代码

### ISSUE THREAD

**Issue by weigeloveu** [kkevsekk1/AutoX#1055]
1. Autox.js 版本：6.6.4
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 14
4. Android 机型：一加12
5. Android 系统类别：coloros
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：无法运行录制脚本，无法生成布局分析代码
8. 报错日志（可选）：
9. 设备信息: 
App version: 6.6.4
App version code: 664
Android build version: U.R4T3.18a86bb-3bd6e-400f2
Android release version: 14
Android SDK version: 34
Android build ID: CPH2581_14.0.0.810(EX01)
Device brand: OnePlus
Device manufacturer: OnePlus
Device name: OP595DL1
Device model: PJD110
Device product name: CPH2581
Device hardware name: qcom
ABIs: [arm64-v8a]
ABIs (32bit): []
ABIs (64bit): [arm64-v8a]

错误信息:
android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ActivityManagerService.registerReceiverWithFeature(ActivityManagerService.java:15038)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2570)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3039)
	at android.os.Binder.execTransactInternal(Binder.java:1362)
	at android.os.Binder.execTransact(Binder.java:1288)

java.lang.SecurityException:org.autojs.autoxjs.v6: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
android.os.Parcel.createExceptionOrNull(Parcel.java:3087)
......
Caused by:
android.os.RemoteException:Remote stack trace:
	at com.android.server.am.ActivityManagerService.registerReceiverWithFeature(ActivityManagerService.java:15038)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2570)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3039)
	at android.os.Binder.execTransactInternal(Binder.java:1362)
	at android.os.Binder.execTransact(Binder.java:1288)

10. 屏幕截图（可选）：

**Comment by Liberations** [comment]
#1058
