### ISSUE TITLE
手机升级成安卓12，运行脚本闪退出错

### ISSUE THREAD

**Issue by hengwuming** [kkevsekk1/AutoX#107]
Version: 491
Android: 31
android.os.RemoteException: Remote stack trace:
 at com.android.server.media.projection.MediaProjectionManagerService$MediaProjection.start(MediaProjectionManagerService.java:553)
 at android.media.projection.IMediaProjection$Stub.onTransact(IMediaProjection.java:137)
 at android.os.Binder.execTransactInternal(Binder.java:1182)
 at android.os.Binder.execTransact(Binder.java:1146)

java.lang.RuntimeException:Failure delivering result ResultInfo{who=null, request=17777, result=-1, data=Intent { (has extras) }} to activity {org.autojs.autojs/org.autojs.autojs.ui.main.MainActivity_}: java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.Set.add(java.lang.Object)' on a null object reference
android.app.ActivityThread.deliverResults(ActivityThread.java:5413)
......
Caused by:
android.os.RemoteException:Remote stack trace:
 at com.android.server.media.projection.MediaProjectionManagerService$MediaProjection.start(MediaProjectionManagerService.java:553)
 at android.media.projection.IMediaProjection$Stub.onTransact(IMediaProjection.java:137)
 at android.os.Binder.execTransactInternal(Binder.java:1182)
 at android.os.Binder.execTransact(Binder.java:1146)

**Comment by GiGaFotress** [comment]
同问题,并且每次崩溃后都需要重设无障碍权限

**Comment by wangxczhangxia** [comment]
我也是同样的问题

**Comment by wangxczhangxia** [comment]
Version: 493
Android: 31
android.os.RemoteException: Remote stack trace:
	at com.android.server.media.projection.MediaProjectionManagerService$MediaProjection.start(MediaProjectionManagerService.java:553)
	at android.media.projection.IMediaProjection$Stub.onTransact(IMediaProjection.java:137)
	at android.os.Binder.execTransactInternal(Binder.java:1182)
	at android.os.Binder.execTransact(Binder.java:1146)

java.lang.RuntimeException:Failure delivering result ResultInfo{who=null, request=17777, result=-1, data=Intent { (has extras) }} to activity {org.autojs.autojs/com.stardust.autojs.core.image.capture.ScreenCaptureRequestActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.Set.add(java.lang.Object)' on a null object reference
android.app.ActivityThread.deliverResults(ActivityThread.java:5446)
......
Caused by:
android.os.RemoteException:Remote stack trace:
	at com.android.server.media.projection.MediaProjectionManagerService$MediaProjection.start(MediaProjectionManagerService.java:553)
	at android.media.projection.IMediaProjection$Stub.onTransact(IMediaProjection.java:137)
	at android.os.Binder.execTransactInternal(Binder.java:1182)
	at android.os.Binder.execTransact(Binder.java:1146)

**Comment by wangxczhangxia** [comment]
我觉得应该是MIUI13或12.5的问题。

**Comment by wingswing1** [comment]
持续关注 正准备升MIUI13 ANDRIOD12 那先不升了 楼主解决了麻烦告知下 谢谢

**Comment by wangxczhangxia** [comment]
你现在用的是哪个版本？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年1月6日(周四) 下午3:45
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [kkevsekk1/AutoX] 手机升级成安卓12，运行脚本闪退出错 (Issue #107)




 
持续关注 正准备升MIUI13 ANDRIOD12 那先不升了 楼主解决了麻烦告知下 谢谢
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by GiGaFotress** [comment]
12.5&nbsp; 13 全这个毛病,我建议你使用安卓11




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年1月6日(星期四) 下午3:45
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [kkevsekk1/AutoX] 手机升级成安卓12，运行脚本闪退出错 (Issue #107)





 
持续关注 正准备升MIUI13 ANDRIOD12 那先不升了 楼主解决了麻烦告知下 谢谢
