### ISSUE TITLE
bug: 打包后打开闪退

### ISSUE THREAD

**Issue by Dream-668** [kkevsekk1/AutoX#1076]
1. Autox.js 版本：664
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 10
4. Android 机型：22081212C
5. Android 系统类别：MIUI
6. VSCODE  扩展版本 Auto.js-Autox.js-VSCodeExt （可选，如果是连接电脑的问题需要填）：
7. 问题描述：打包后打开闪退
8. 报错日志（可选）：java.lang.UnsatisfiedLinkError: dlopen failed: library "libjackpal-termexec2.so" not found
	at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
	at java.lang.Runtime.loadLibrary0(Runtime.java:998)
	at java.lang.System.loadLibrary(System.java:1661)
	at jackpal.androidterm.TermExec.<clinit>(TermExec.java:22)
	at jackpal.androidterm.TermExec.createSubprocess(TermExec.java:106)
	at jackpal.androidterm.ShellTermSession.createSubprocess(ShellTermSession.java:153)
	at jackpal.androidterm.ShellTermSession.initializeSession(ShellTermSession.java:101)
	at jackpal.androidterm.ShellTermSession.<init>(ShellTermSession.java:57)
	at com.stardust.autojs.core.util.Shell$MyShellTermSession.<init>(Shell.java:220)
	at com.stardust.autojs.core.util.Shell.lambda$init$0(Shell.java:101)
	at com.stardust.autojs.core.util.Shell.$r8$lambda$XphcqSP4sHMFI662Ue0FDKvnGyg(Unknown Source:0)
	at com.stardust.autojs.core.util.Shell$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Unknown Source:2)
	at android.os.Handler.dispatchMessage(Unknown Source:4)
	at android.os.Looper.loopOnce(Unknown Source:182)
	at android.os.Looper.loop(Unknown Source:82)
	at android.app.ActivityThread.main(Unknown Source:123)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
	at com.android.internal.os.ZygoteInit.main(Unknown Source:312)

9. 屏幕截图（可选）：

**Comment by Delta-Water** [comment]
同样，同问

**Comment by Gsq123-G** [comment]
同问
