### ISSUE TITLE
在最新的7.0.1版本中，无法通过launch、launchapp等接口调用其他app，在此之前版本是可以调用的

### ISSUE THREAD

**Issue by LMTXQ** [kkevsekk1/AutoX#1117]
1. Autox.js 版本：7.0.1
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 13 、Android 9
4. Android 机型：红米k40、中国移动云手机、以及部分其他人员反馈
5. Android 系统类别：MIUI、云手机应该是定制系统
7. 问题描述：在最新的7.0.1版本中，无法通过launch、launchapp等接口调用其他app，在此之前版本是可以调用的，目前我测试的多部手机都无法调用，测试原6.6.6版本可以正常调用
8. 报错日志（可选）：无明显报错，仅是运行语句无反应
9. 屏幕截图（可选）：
![4c225020c155c198f6e1defffb0c851e](https://github.com/user-attachments/assets/2bfea3c6-b49d-4837-864c-aaff00c1095e)
![b9c4599559b1a41fff31db8136d14b9f](https://github.com/user-attachments/assets/8131c1a5-8ff0-4558-b378-14ba23305fa7)
![ee7297faab79cb536fa862dd98af67cd](https://github.com/user-attachments/assets/f00ec57b-a8d8-4fad-b9f2-e46ea604777e)

目前我测试了一下以下所有软件，包含autox.js V7和autox.js V6,仅autox.js V7有此问题
![e8369865a7637391310587ba0ef0c4b2](https://github.com/user-attachments/assets/8283cd6f-4caa-44a9-ab84-7155766c1163)

另外：请问一下，autox.js有接入Android X库的可能吗？我目前使用了上述所有软件，发现仅autojs6支持了Android X库，其他软件在我引入    importClass(androidx.viewpager.widget.PagerAdapter);
    importClass(androidx.viewpager.widget.ViewPager);时都会报一个androidx未定义的错，很难受

最后，感谢所有的项目贡献者

**Comment by kkevsekk1** [comment]
理论上是支持的



发送自我的盖乐世



-------- 原始信息 --------
发件人： 三金you木 ***@***.***>
日期: 2024/8/8 23:53 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： Subscribed ***@***.***>
主题： [kkevsekk1/AutoX] 在最新的7.0.1版本中，无法通过launch、launchapp等接口调用其他app，在此之前版本是可以调用的 (Issue #1117)


  1.  Autox.js 版本：7.0.1
  2.  Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
  3.  Android 版本：Android 13 、Android 9
  4.  Android 机型：红米k40、中国移动云手机、以及部分其他人员反馈
  5.  Android 系统类别：MIUI、云手机应该是定制系统
  6.  问题描述：在最新的7.0.1版本中，无法通过launch、launchapp等接口调用其他app，在此之前版本是可以调用的，目前我测试的多部手机都无法调用，测试原6.6.6版本可以正常调用
  7.  报错日志（可选）：无明显报错，仅是运行语句无反应
  8.  屏幕截图（可选）：
4c225020c155c198f6e1defffb0c851e.png (view on web)<https://github.com/user-attachments/assets/2bfea3c6-b49d-4837-864c-aaff00c1095e>
b9c4599559b1a41fff31db8136d14b9f.jpg (view on web)<https://github.com/user-attachments/assets/8131c1a5-8ff0-4558-b378-14ba23305fa7>
ee7297faab79cb536fa862dd98af67cd.jpg (view on web)<https://github.com/user-attachments/assets/f00ec57b-a8d8-4fad-b9f2-e46ea604777e>

目前我测试了一下以下所有软件，包含autox.js V7和autox.js V6,仅autox.js V7有此问题
e8369865a7637391310587ba0ef0c4b2.jpg (view on web)<https://github.com/user-attachments/assets/8283cd6f-4caa-44a9-ab84-7155766c1163>

另外：请问一下，autox.js有接入Android X库的可能吗？我目前使用了上述所有软件，发现仅autojs6支持了Android X库，其他软件在我引入 importClass(androidx.viewpager.widget.PagerAdapter);
importClass(androidx.viewpager.widget.ViewPager);时都会报一个androidx未定义的错，很难受

最后，感谢所有的项目贡献者

―

**Comment by aiselp** [comment]
launchapp相关函数确实有问题，androidx应该是没有定义成全局变量，使用`Packages.androidx`

**Comment by fengxujun330** [comment]
之前的launch app相关函数也是有问题。每次launch都是新打开app，应该加个“如果app已经启动则不新启动app而是将app调到前台”接口。

**Comment by LMTXQ** [comment]
> launchapp相关函数确实有问题，androidx应该是没有定义成全局变量，使用`Packages.androidx`

非常感谢，使用`Packages.androidx`后的确可以使用androidx库了

**Comment by aiselp** [comment]
tasks是什么？这个错误只是表明有Promise状态变为rejection并且有被处理

**Comment by LMTXQ** [comment]
> tasks是什么？这个错误只是表明有Promise状态变为rejection并且有被处理

我看了一下，tasks.queryTimedTasks和tasks.addDailyTask这些用于查询添加删除定时任务的接口好像是autojs和autojs6那边提供的，autox.js这边没有提供


想请教一下，在autox.js中，通过代码来添加定时任务只有下面这一种笨方法吗
![ed7314c0-33cd-4e97-b285-ed592a60215c](https://github.com/user-attachments/assets/e6817e45-8c99-4126-89db-f1dbe297cd16)

**Comment by LMTXQ** [comment]
> tasks是什么？这个错误只是表明有Promise状态变为rejection并且有被处理

我需要使用的queryTimedTasks和addDailyTask这些用于增删改查定时任务的接口
在auto6.js中，根据其开发文档可以知道使用方法：tasks.queryTimedTasks({path: jsPath})
在autojs Pro中，根据其开发文档也可以知道使用方法：timers.queryTimedTasks({path: jsPath})
tasks或timers都是它们直接提供的变量，但在autox.js的开发文档中，我没找到相应接口的使用方法，而使用上述的两种方式都无法使用，请问在autox.js中，这个接口要如何使用呢？

我目前对Autojs6和AutojsPro的兼容方法（我翻遍了手册也没找到Autox.js的接口）：
![18bada61-5dbd-4cfd-8c2c-c5c7c258a1a7](https://github.com/user-attachments/assets/e41078a0-baf5-4eed-9f9e-9b94612f5ba2)

感谢大佬 @aiselp @kkevsekk1

**Comment by aiselp** [comment]
autox中还没有相关api

三金you木 ***@***.***> 于 2024年8月18日周日 15:35写道：

**Comment by LMTXQ** [comment]
好吧，感谢解答

**Comment by yanweimin7** [comment]
> > launchapp相关函数确实有问题，androidx应该是没有定义成全局变量，使用`Packages.androidx`
> 
> 非常感谢，使用`Packages.androidx`后的确可以使用androidx库了

请问下用androidx是怎么调用launch的

**Comment by hnty545** [comment]
我也是这个问题，请问Packages.androidx如何使用让launch可行，这个问题是在小米澎湃OS上遇到的，launch返回false，getPackageName、getAppName都返回null，获取应用列表权限是允许的，看权限记录也是允许记录，目前就卡在这里，请求帮助，谢谢！

**Comment by hnty545** [comment]
我的澎湃OS版本是1.0.5.0，安卓版本是13

**Comment by CAH-FlyChen** [comment]
我也是同样问题 getPackageName 返回null

**Comment by hnty545** [comment]
> > launchapp相关函数确实有问题，androidx应该是没有定义成全局变量，使用`Packages.androidx`
> 
> 非常感谢，使用`Packages.androidx`后的确可以使用androidx库了

请教你怎么解决的，如何使用Packages.androidx让launch起作用的？谢谢！

**Comment by maryjeck** [comment]
> > launchapp相关函数确实有问题，androidx应该是没有定义成全局变量，使用`Packages.androidx`
> 
> 非常感谢，使用`Packages.androidx`后的确可以使用androidx库了

请教一下，您怎么解决的？

**Comment by fhqfhvtx** [comment]
7.0.5也存在同样的问题，launch和launchApp。传递app名称或者报名都报错
10:35:40.322/E: Wrapped java.lang.SecurityException: 没有读取设备信息权限 (/data/user/0/org.autojs.autoxjs.v7/cache/remote/remote-main.js#366)
Wrapped java.lang.SecurityException: 没有读取设备信息权限
    at /data/user/0/org.autojs.autoxjs.v7/cache/remote/remote-main.js:366:0
    at /data/user/0/org.autojs.autoxjs.v7/cache/remote/remote-main.js:360:0
    at main (/data/user/0/org.autojs.autoxjs.v7/cache/remote/remote-main.js:514:0)
    at /data/user/0/org.autojs.autoxjs.v7/cache/remote/remote-main.js:516:0
    at _0x4fc63a (/data/user/0/org.autojs.autoxjs.v7/cache/remote/remote-main.js:163:0)
    at /data/user/0/org.autojs.autoxjs.v7/cache/remote/remote-main.js:165:0
    at /data/user/0/org.autojs.autoxjs.v7/cache/remote/remote-main.js:152:0
