### ISSUE TITLE
最新版本7.0.2获取设备的宽高都为0

### ISSUE THREAD

**Issue by qwe317149766** [kkevsekk1/AutoX#1138]
`3:24:45.470/V: 开始运行[/storage/emulated/0/脚本/fb.js]
13:24:45.477/D: params.cacheName tiktokCache
13:24:50.735/D: 0 'device.width'
13:24:50.736/D: 0 'device.height'
13:24:50.736/D: device: 0 0
13:24:50.737/D: 0 0
13:24:50.757/E: Wrapped CvException [org.opencv.core.CvException: cv::Exception: OpenCV(4.5.5) /build/master_pack-android/opencv/modules/imgproc/src/resize.cpp:4055: error: (-215:Assertion failed) inv_scale_x > 0 in function 'resize'
] (/android_asset/modules/__images__.js#306)
Wrapped CvException [org.opencv.core.CvException: cv::Exception: OpenCV(4.5.5) /build/master_pack-android/opencv/modules/imgproc/src/resize.cpp:4055: error: (-215:Assertion failed) inv_scale_x > 0 in function 'resize'
]
    at /android_asset/modules/__images__.js:306:0
    at findImgClick (/storage/emulated/0/脚本/common.js:830:0)
    at /storage/emulated/0/脚本/fb.js:6:0

**Comment by aiselp** [comment]
打印device.width是正常的

**Comment by mouuii** [comment]
我也遇到这问题了，咋回事

**Comment by mouuii** [comment]
有人吗

**Comment by xxl-cc** [comment]
同样的问题，我打印出来也是0

**Comment by Yuan-ZW** [comment]
1. Autox.js 版本：7.0.4
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 13
4. Android 机型：小米10
5. Android 系统类别：Hyper OS

一样的问题 device.width 和 device.height 都是0

**Comment by steelywing** [comment]
Try

```js
console.log(Packages.android.content.res.Resources.getSystem().getDisplayMetrics().widthPixels);
console.log(Packages.android.content.res.Resources.getSystem().getDisplayMetrics().heightPixels);
```

Relate: https://github.com/kkevsekk1/AutoX/issues/1246#issuecomment-2444376357

**Comment by Yuan-ZW** [comment]
> Try
> 
> ```js
> console.log(Packages.android.content.res.Resources.getSystem().getDisplayMetrics().widthPixels);
> console.log(Packages.android.content.res.Resources.getSystem().getDisplayMetrics().heightPixels);
> ```
> 
> Relate: [#1246 (comment)](https://github.com/kkevsekk1/AutoX/issues/1246#issuecomment-2444376357)

有用 !
不过有个问题, 这样获得的高度和原本的 `device.height` 之间差了一个状态栏高度

所以最后我是这样实现的:
```js
// 获取状态栏高度 (忘了从哪抄来的了, 但是好用)
function getStatusBarHeight() {
  let result = 0
  let resId = context.getResources().getIdentifier('status_bar_height', 'dimen', 'android')
  if (resId > 0) {
    result = context.getResources().getDimensionPixelOffset(resId)
  }
  if (result <= 0) {
    result = context.getResources().getDimensionPixelOffset(R.dimen.dimen_25dp)
  }
  return result
}

// 获取屏幕宽高
function getDeviceSize() {
  let displayMetrics = Packages.android.content.res.Resources.getSystem().getDisplayMetrics()
  return {
    width: displayMetrics.widthPixels,
    height: displayMetrics.heightPixels + getStatusBarHeight(),
  }
}

let deviceSize = getDeviceSize()

console.log(deviceSize)
```
