### ISSUE TITLE
通过系统快捷开关布局范围分析，会导致无障碍关闭

### ISSUE THREAD

**Issue by 15103100** [kkevsekk1/AutoX#1152]
Autox.js 版本：6.6.6
Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
Android 版本：Android 14
Android 机型：红米K40Pro+
Android 系统类别：澎湃OS 1.0.2.0
VSCODE 扩展版本 Auto.js-Autox.js-VSCodeExt （可选，如果是连接电脑的问题需要填）：
问题描述：通过系统快捷开关布局范围分析，会导致无障碍关闭，必现
报错日志（可选）：无
屏幕截图（可选）：无

**Comment by isdkz** [comment]
我也有这个问题，这是我的报错日志：

设备信息: 
App version: 6.6.7
App version code: 667
Android build version: U.197f1c5-a4-21fca
Android release version: 14
Android SDK version: 34
Android build ID: PJX110_14.1.0.403(CN01)
Device brand: OnePlus
Device manufacturer: OnePlus
Device name: OP5D06L1
Device model: PJX110
Device product name: PJX110
Device hardware name: qcom
ABIs: [arm64-v8a]
ABIs (32bit): []
ABIs (64bit): [arm64-v8a]

错误信息:
android.os.RemoteException: Remote stack trace:
	at com.android.server.wm.ActivityTaskManagerService.checkCanCloseSystemDialogs(ActivityTaskManagerService.java:3369)
	at com.android.server.wm.ActivityTaskManagerService$LocalService.checkCanCloseSystemDialogs(ActivityTaskManagerService.java:6347)
	at com.android.server.am.ActivityManagerService.broadcastIntentLockedTraced(ActivityManagerService.java:16057)
	at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:15517)
	at com.android.server.am.ActivityManagerService.broadcastIntentWithFeature(ActivityManagerService.java:16577)

java.lang.SecurityException:Permission Denial: android.intent.action.CLOSE_SYSTEM_DIALOGS broadcast from org.autojs.autoxjs.v6 (pid=18814, uid=10537) requires android.permission.BROADCAST_CLOSE_SYSTEM_DIALOGS.
android.os.Parcel.createExceptionOrNull(Parcel.java:3087)
......
Caused by:
android.os.RemoteException:Remote stack trace:
	at com.android.server.wm.ActivityTaskManagerService.checkCanCloseSystemDialogs(ActivityTaskManagerService.java:3369)
	at com.android.server.wm.ActivityTaskManagerService$LocalService.checkCanCloseSystemDialogs(ActivityTaskManagerService.java:6347)
	at com.android.server.am.ActivityManagerService.broadcastIntentLockedTraced(ActivityManagerService.java:16057)
	at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:15517)
	at com.android.server.am.ActivityManagerService.broadcastIntentWithFeature(ActivityManagerService.java:16577)
