### ISSUE TITLE
安卓 14 上 Paint.setColor() 方法报错

### ISSUE THREAD

**Issue by pansong291** [kkevsekk1/AutoX#1182]
1. Autox.js 版本：664
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 14
4. Android 机型：小米13
5. Android 系统类别：MIUI

代码如下：
```jsx
const window = floaty.window(
  <frame gravity="center">
      <text id="text" text="点击可调整位置" textSize="16sp"/>
      <canvas id="board" w="*" h="*"/>
  </frame>
);

window.exitOnClose();

window.text.click(()=>{
  window.setAdjustEnabled(!window.isAdjustEnabled());
});

//画笔
var paint = new Paint();
//设置画笔颜色
paint.setColor(colors.parseColor("#ff0ff0ff"));

window.board.on("draw", function(canvas){
    var w = canvas.getWidth();
    var h = canvas.getHeight();
    canvas.drawRect(200,200,500,500,paint);
});
setInterval(()=>{}, 1000);
```
```
22:59:46.174/E: Wrapped java.lang.IllegalArgumentException: Invalid ID, must be in the range [0..18) (/storage/emulated/0/脚本/test.js#17)
Wrapped java.lang.IllegalArgumentException: Invalid ID, must be in the range [0..18)
    at /storage/emulated/0/脚本/test.js:17:0
```

然后我把设置颜色那里的代码改成了这样的字符串：
```js
paint.setColor("#ff0ff0ff");
```
得到如下报错：
```
23:05:58.254/E: The choice of Java method android.graphics.Paint.setColor matching JavaScript argument types (string) is ambiguous; candidate methods are: 
    void setColor(int)
    void setColor(long) (/storage/emulated/0/脚本/test.js#17)
The choice of Java method android.graphics.Paint.setColor matching JavaScript argument types (string) is ambiguous; candidate methods are: 
    void setColor(int)
    void setColor(long)
    at /storage/emulated/0/脚本/test.js:17:0
```

**Comment by pansong291** [comment]
这是 Rhino 无法解决的一个痛点，目前的解决办法：
https://github.com/kkevsekk1/AutoX/issues/1180#issuecomment-2339471235

**Comment by pansong291** [comment]
看起来似乎是优先调用了 `setColor(long)` 才报的错。

那么可能的解决方案：

```js
try {
    paint.setColor(colors.pack(colors.parseColor("#ff0ff0ff")));
} catch(e) {
    paint.setColor(colors.parseColor("#ff0ff0ff"));
}
```
其中 colors.pack 详见 https://developer.android.google.cn/reference/android/graphics/Color#pack(int)

**Comment by aiselp** [comment]
> @kkevsekk1
> 
> 原因是 Android O 及之后，`Paint` 类的 `setColor` 方法被重载了，有两个签名：
> 
> ```
> public void setColor(int i);
> public void setColor(long l);
> ```
> 
> Rhino 无法判断应该调用哪一个。这是 Rhino 无法解决的一个痛点，目前的解决办法： [#1180 (comment)](https://github.com/kkevsekk1/AutoX/issues/1180#issuecomment-2339471235)

Rhino重载问题确实不好解决，受你提供的示例启发，我发现可以直接使用反射来解决
```js
var Integer = java.lang.Integer;
var paint = new Paint();
paint
  .getClass()
  .getMethod("setColor", Integer.TYPE)
  .invoke(paint, Integer.valueOf(colors.parseColor("#cc0ff0ff")));

```

**Comment by pansong291** [comment]
@aiselp 反射是我最开始尝试的方法，如下代码：
```javascript
Packages.java.lang.Class.forName('android.graphics.Paint')
    .getMethod('setColor', Packages.java.lang.Integer.TYPE)
    .invoke(paint, color)
```
很遗憾，上面这个代码是不行的，仍然会报错：
```
Wrapped java.lang.IllegalArgumentException: Invalid ID, must be in the range [0..18)
```
这里的 `color` 并没有使用 `Integer` 进行包装，所以它传入的值还是会被转为 `long`。
不知道包装后能不能行得通，我没有测试过。

**Comment by aiselp** [comment]
> @aiselp 反射是我最开始尝试的方法，如下代码：
> 
> ```js
> Packages.java.lang.Class.forName('android.graphics.Paint')
>     .getMethod('setColor', Packages.java.lang.Integer.TYPE)
>     .invoke(paint, color)
> ```
> 
> 很遗憾，上面这个代码是不行的，仍然会报错。 这里的 `color` 并没有使用 `Integer` 进行包装，所以它传入的值还是会被转为 `long`。 不知道包装后能不能行得通，我没有测试过。 如果可行的话，可以这么写：
> 
> ```js
> paint.setColor(Packages.java.lang.Integer.valueOf(colors.parseColor("#ff0ff0ff")))
> ```

我测了必须使用反射+包装类型才能避免被转换，直接传入包装类型也不行

**Comment by pansong291** [comment]
> 我测了必须使用反射+包装类型才能避免被转换，直接传入包装类型也不行。
> 第一种由于js中数值是Double，直接传入数值会报错参数不符。
> 第二种还是被转换成Long

@aiselp 反射调用是因为 `invoke()` 方法的形参是 `Object[]`，然后传入的实参是 `Integer`，这样的话我猜测可能 Rhino 就没有去做类型转换，如果是普通方法 `setColor()`，虽然实参是 `Integer`，但 Rhino 仍然做了类型转换？

**Comment by aiselp** [comment]
> > 我测了必须使用反射+包装类型才能避免被转换，直接传入包装类型也不行。
> > 第一种由于js中数值是Double，直接传入数值会报错参数不符。
> > 第二种还是被转换成Long
> 
> @aiselp 反射调用是因为 `invoke()` 方法的形参是 `Object[]`，然后传入的实参是 `Integer`，这样的话我猜测可能 Rhino 就没有去做类型转换，如果是普通方法 `setColor()`，虽然实参是 `Integer`，但 Rhino 仍然做了类型转换？

大概就是这样，Rhino优先获取到的方法是接收Long的，而Integer是可以无损转换成Long就直接使用此方法了，而没有再去判断其他方法是否有更优选择

**Comment by pansong291** [comment]
附：自定义 View 的 js 实现

https://github.com/kkevsekk1/AutoX/issues/1179#issuecomment-2475934927
