### ISSUE TITLE
shell 函数执行input tap命令提示没有权限

### ISSUE THREAD

**Issue by zhouyinxuan9264** [kkevsekk1/AutoX#1216]
1. Autox.js 版本：667
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 14
4. Android 机型：vivo
5. Android 系统类别：originos4
6. VSCODE  扩展版本 Auto.js-Autox.js-VSCodeExt （可选，如果是连接电脑的问题需要填）：
7. 问题描述：想要模拟触摸动作，但是没有root权限，于是使用函数shell(' input tap x y') 日志提示没有权限，除此之外很多不需要root权限的shell命令也执行不了，用adb连接执行是正常的
8. 报错日志（可选）：23:42:42.954/D: ShellResult{code=255, error='
Exception occurred while executing 'tap':
java.lang.SecurityException: Injecting input events requires the caller (or the source of the instrumentation, if any) to have the INJECT_EVENTS permission.
	at com.android.server.input.InputManagerService.injectInputEventToTarget(InputManagerService.java:1060)
	at android.hardware.input.InputManagerGlobal.injectInputEvent(InputManagerGlobal.java:1234)
	at android.hardware.input.InputManagerGlobal.injectInputEvent(InputManagerGlobal.java:1244)
	at com.android.server.input.InputShellCommand.injectMotionEvent(InputShellCommand.java:182)
	at com.android.server.input.InputShellCommand.sendTap(InputShellCommand.java:383)
	at com.android.server.input.InputShellCommand.runTap(InputShellCommand.java:377)
	at com.android.server.input.InputShellCommand.onCommand(InputShellCommand.java:236)
	at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)
	at android.os.ShellCommand.exec(ShellCommand.java:38)
	at com.android.server.input.InputManagerService.onShellCommand(InputManagerService.java:3747)
	at android.os.Binder.shellCommand(Binder.java:1134)
	at android.os.Binder.onTransact(Binder.java:954)
	at android.hardware.input.IInputManager$Stub.onTransact(IInputManager.java:1550)
	at android.os.Binder.execTransactInternal(Binder.java:1410)

9. 屏幕截图（可选）：
![Screenshot_20240930_091705](https://github.com/user-attachments/assets/02f176ee-e487-4b18-aae9-ee097a34e353)
![Screenshot_20240930_091702](https://github.com/user-attachments/assets/503e69d3-a844-49e7-a0a6-02007e6ba6e3)

**Comment by aiselp** [comment]
此命令需要root或adb shell同等权限
