### ISSUE TITLE
7.0.4用VSCode调试时 require 报错, 相比v6版本, 工作目录cwd变了

### ISSUE THREAD

**Issue by Yuan-ZW** [kkevsekk1/AutoX#1249]
1. Autox.js 版本：704
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 13
4. Android 机型：小米10
5. Android 系统类别：HyperOS 1
6. VSCODE  扩展版本 Auto.js-Autox.js-VSCodeExt：v1.110.0
7. 问题描述：

已将 v6 和 v7 内 **`更改脚本文件夹路径`** 设置为相同的目录
然后运行同样的一份代码:
```js
console.log(files.cwd());

const utils = require('./utils.js') // 这个脚本已经放在了手机上
```
### v6 正常
```
11:15:48.185/V: 开始运行[[remote]t.js]
11:15:48.186/D: /storage/emulated/0/_ftp/autoxjs
11:15:48.194/V: 
 ------------ 
 [ [remote]t.js ]运行结束，用时0.008000秒
```

### v7 异常
```
11:16:30.292/V: 开始运行[/data/user/0/org.autojs.autoxjs.v7/cache/remote/remote-t.js]
11:16:30.295/D: /data/user/0/org.autojs.autoxjs.v7/cache/remote
11:16:30.301/E: Error: Can't resolve relative module ID "./utils.js" when require() is used outside of a module (/android_asset/modules/jvm-npm.js#87)
Error: Can't resolve relative module ID "./utils.js" when require() is used outside of a module
    at Require (/android_asset/modules/jvm-npm.js:87:0)
    at /data/user/0/org.autojs.autoxjs.v7/cache/remote/remote-t.js:3:0

11:16:30.301/V: 
------------
[/data/user/0/org.autojs.autoxjs.v7/cache/remote/remote-t.js]运行结束，用时0.009000秒
```

很明显 看起来是 v7 上执行的远程脚本被映射到手机上不同的目录里导致的

有什么办法在 v7 上保持以这种方式调试吗? _懒得用webpack之类工具的打包_

**Comment by aiselp** [comment]
点运行项目，别按F5

**Comment by Yuan-ZW** [comment]
> 点运行项目，别按F5

![动画](https://github.com/user-attachments/assets/7396ec14-9e47-4eb2-9f97-727bead7dfc9)

你是说运行脚本吗, 和F5的效果是一样的

**Comment by wunaidejianao** [comment]
> > 点运行项目，别按F5
> 
> ![动画](https://private-user-images.githubusercontent.com/31435244/382626769-7396ec14-9e47-4eb2-9f97-727bead7dfc9.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3MTQ0NTUsIm5iZiI6MTczMDcxNDE1NSwicGF0aCI6Ii8zMTQzNTI0NC8zODI2MjY3NjktNzM5NmVjMTQtOWU0Ny00ZWIyLTlmOTctNzI3YmVhZDdkZmM5LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA0VDA5NTU1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0NmEwNjZkMDk0NmZkYTI2OTQ3NWFkNjk3YTUxNzI0YjQwN2FkOWFmNzQ1MThkZDhmZmVlMDQ4MTUzNGU1MzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.OIvMFnoM7KYYtw5CPDl33lpRPn6N_plN5G_LIGIs2uc) [ ![动画](https://private-user-images.githubusercontent.com/31435244/382626769-7396ec14-9e47-4eb2-9f97-727bead7dfc9.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3MTQ0NTUsIm5iZiI6MTczMDcxNDE1NSwicGF0aCI6Ii8zMTQzNTI0NC8zODI2MjY3NjktNzM5NmVjMTQtOWU0Ny00ZWIyLTlmOTctNzI3YmVhZDdkZmM5LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA0VDA5NTU1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0NmEwNjZkMDk0NmZkYTI2OTQ3NWFkNjk3YTUxNzI0YjQwN2FkOWFmNzQ1MThkZDhmZmVlMDQ4MTUzNGU1MzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.OIvMFnoM7KYYtw5CPDl33lpRPn6N_plN5G_LIGIs2uc) ](https://private-user-images.githubusercontent.com/31435244/382626769-7396ec14-9e47-4eb2-9f97-727bead7dfc9.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3MTQ0NTUsIm5iZiI6MTczMDcxNDE1NSwicGF0aCI6Ii8zMTQzNTI0NC8zODI2MjY3NjktNzM5NmVjMTQtOWU0Ny00ZWIyLTlmOTctNzI3YmVhZDdkZmM5LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA0VDA5NTU1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0NmEwNjZkMDk0NmZkYTI2OTQ3NWFkNjk3YTUxNzI0YjQwN2FkOWFmNzQ1MThkZDhmZmVlMDQ4MTUzNGU1MzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.OIvMFnoM7KYYtw5CPDl33lpRPn6N_plN5G_LIGIs2uc) [ ](https://private-user-images.githubusercontent.com/31435244/382626769-7396ec14-9e47-4eb2-9f97-727bead7dfc9.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3MTQ0NTUsIm5iZiI6MTczMDcxNDE1NSwicGF0aCI6Ii8zMTQzNTI0NC8zODI2MjY3NjktNzM5NmVjMTQtOWU0Ny00ZWIyLTlmOTctNzI3YmVhZDdkZmM5LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA0VDA5NTU1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0NmEwNjZkMDk0NmZkYTI2OTQ3NWFkNjk3YTUxNzI0YjQwN2FkOWFmNzQ1MThkZDhmZmVlMDQ4MTUzNGU1MzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.OIvMFnoM7KYYtw5CPDl33lpRPn6N_plN5G_LIGIs2uc)
> 
> 你是说运行脚本吗, 和F5的效果是一样的

不，按 Ctrl + Shift + P,再搜项目就能找到。

**Comment by wunaidejianao** [comment]
不，按 Ctrl + Shift + P,再搜项目就能找到。

**Comment by Yuan-ZW** [comment]
![动画](https://github.com/user-attachments/assets/96fd68fd-82f5-4295-90c2-7cfb40609447)

运行项目似乎没有任何效果，关于项目的使用哪里有文档说明吗？

**Comment by wunaidejianao** [comment]
http://doc.autoxjs.com/#/qa?id=%e5%a6%82%e4%bd%95%e6%8a%8a%e5%9b%be%e7%89%87%e5%92%8c%e8%84%9a%e6%9c%ac%e4%b8%80%e8%b5%b7%e6%89%93%e5%8c%85%ef%bc%8c%e6%88%96%e8%80%85%e6%89%93%e5%8c%85%e5%a4%9a%e4%b8%aa%e8%84%9a%e6%9c%ac

**Comment by Yuan-ZW** [comment]
> 当前的最新版我试了，在 Auto.js-Autox.js-VSCodeExt-Wilinz 上运行项目没反应。

我说呢😂

那回到我一开始的问题，调试脚本似乎还是不太方便
