### ISSUE TITLE
events.observeNotification();报错

### ISSUE THREAD

**Issue by yongplus** [kkevsekk1/AutoX#1263]
1. Autox.js 版本：7.0.4
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 10
4. Android 机型：小米10，VIVO
5. Android 系统类别：MIUI
6. VSCODE  扩展版本 Auto.js-Autox.js-VSCodeExt （可选，如果是连接电脑的问题需要填）：
7. 问题描述：7.0.4调用上述接口报错, 6版本没问题
8. 报错日志（可选）：
```
09:13:41.906/E: Wrapped android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want? (/data/user/0/org.autojs.autoxjs.v7/cache/remote/remote-main.js#850)
Wrapped android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
    at /data/user/0/org.autojs.autoxjs.v7/cache/remote/remote-main.js:850:0
    at _0x4f8590 (/data/user/0/org.autojs.autoxjs.v7/cache/remote/remote-main.js:846:0)
    at _0x7cfacf (/data/user/0/org.autojs.autoxjs.v7/cache/remote/remote-main.js:862:0)
    at main (/data/user/0/org.autojs.autoxjs.v7/cache/remote/remote-main.js:1182:0)
    at /data/user/0/org.autojs.autoxjs.v7/cache/remote/remote-main.js:1184:0
    at _0xb32efd (/data/user/0/org.autojs.autoxjs.v7/cache/remote/remote-main.js:26:0)
    at /data/user/0/org.autojs.autoxjs.v7/cache/remote/remote-main.js:28:0
    at /data/user/0/org.autojs.autoxjs.v7/cache/remote/remote-main.js:15:0
```
10. 屏幕截图（可选）：

**Comment by april-ocean** [comment]
解决了吗，我爷爷到这个问题了

**Comment by zhuluquan** [comment]
解决了吗，我也遇到这个问题

**Comment by yongplus** [comment]
解决了，“通知使用权“”和“通知权限“搞混淆了，在设置搜索“使用权”，会看到通知使用权，开启即可。

**Comment by yongplus** [comment]
Fixed
