### ISSUE TITLE
UI 模式脚本执行结果为 null 时触发空指针异常

### ISSUE THREAD

**Issue by SuperMonster003** [kkevsekk1/AutoX#1264]
```javascript
"ui";
null
```

```text
Parameter specified as non-null is null: method com.stardust.autojs.execution.ScriptExecuteActivity$doExecution$1.onResult, parameter r
```

https://github.com/kkevsekk1/AutoX/blob/0aefe5a8a49a787e9e4b9ec14ea80491f6f98489/autojs/src/main/java/com/stardust/autojs/execution/ScriptExecuteActivity.kt#L86

**Comment by huangjinhong** [comment]
同样出现这个问题，无法使用，v7.0.5版本
let outInput = id("g2s").findOne();
if (outInput) {
    console.log('outInput: ' + outInput);
    outInput.click();
}

报错：
java.lang.NullPointerException: Parameter specified as non-null is null: method com.stardust.autojs.rhino.AndroidContextFactory$WrapFactory.wrap, parameter scope
	at com.stardust.autojs.rhino.AndroidContextFactory$WrapFactory.wrap(Unknown Source:7)
	at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:227)
	at org.mozilla.javascript.ScriptableObject.getDefaultValue(ScriptableObject.java:791)
	at org.mozilla.javascript.ScriptableObject.getDefaultValue(ScriptableObject.java:766)
	at org.mozilla.javascript.ScriptRuntime.toString(ScriptRuntime.java:1010)
	at org.mozilla.javascript.ScriptRuntime.notFunctionError(ScriptRuntime.java:4651)
	at org.mozilla.javascript.ScriptRuntime.getPropFunctionAndThisHelper(ScriptRuntime.java:2585)
	at org.mozilla.javascript.ScriptRuntime.getPropFunctionAndThis(ScriptRuntime.java:2568)
	at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1666)
	at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:1061)
	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:90)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:380)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3869)
	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:88)
	at org.mozilla.javascript.ArrowFunction.call(ArrowFunction.java:43)
	at com.stardust.autojs.runtime.ScriptBridges$callFunction$1.invoke(ScriptBridges.kt:42)
	at com.stardust.autojs.runtime.ScriptBridges$callFunction$1.invoke(ScriptBridges.kt:37)
	at com.stardust.autojs.runtime.ScriptBridges.useJsContext(ScriptBridges.kt:31)
	at com.stardust.autojs.runtime.ScriptBridges.callFunction(ScriptBridges.kt:37)
	at com.stardust.autojs.core.looper.Timer.callFunction(Timer.kt:40)
	at com.stardust.autojs.core.looper.Timer.access$callFunction(Timer.kt:14)
	at com.stardust.autojs.core.looper.Timer$setInterval$r$1.run(Timer.kt:63)
	at android.os.Handler.handleCallback(Handler.java:900)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:219)
	at com.stardust.autojs.engine.LoopBasedJavaScriptEngine.execute(LoopBasedJavaScriptEngine.java:61)
	at com.stardust.autojs.engine.LoopBasedJavaScriptEngine.execute(LoopBasedJavaScriptEngine.java:34)
	at com.stardust.autojs.execution.LoopedBasedJavaScriptExecution.doExecution(LoopedBasedJavaScriptExecution.java:42)
	at com.stardust.autojs.execution.RunnableScriptExecution.execute(RunnableScriptExecution.java:43)
	at com.stardust.autojs.execution.RunnableScriptExecution.execute(RunnableScriptExecution.java:37)
	at com.stardust.autojs.execution.RunnableScriptExecution.run(RunnableScriptExecution.java:31)
	at java.lang.Thread.run(Thread.java:929)
