### ISSUE TITLE
705无法正常执行项目代码

### ISSUE THREAD

**Issue by zimoyin** [kkevsekk1/AutoX#1267]
1. Autox.js 版本：7.0.5
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 9
4. Android 机型：逍遥模拟器
5. Android 系统类别：逍遥模拟器
6. VSCODE  扩展版本 Auto.js-Autox.js-VSCodeExt （可选，如果是连接电脑的问题需要填）：
7. 问题描述：  
不能正常执行项目，除非 project.json 中 `sourcePath` 字段指定了 main.js 路径。该BUG 同时影响到 vscode 插件，他让插件无法远程执行项目
9. 报错日志（可选）：  
```
2024-11-14 15:43:21.806  2130-17271 GooglePlayServicesUtil  org.autojs.autoxjs.v7                W  org.autojs.autoxjs.v7 requires the Google Play Store, but it is missing.
2024-11-14 15:43:21.806  2130-2130  TimedTaskScheduler      org.autojs.autoxjs.v7                D  The currently enabled scheduled task method is Work Manager
2024-11-14 15:43:21.828  2130-2491  EGL_adreno              org.autojs.autoxjs.v7                E  [getAttribValue] Bad attribute idx
2024-11-14 15:43:21.828  2130-2491  EGL_adreno              org.autojs.autoxjs.v7                D  eglGetConfigAttrib: bad attrib 0x3339
2024-11-14 15:43:22.908  2204-9387  ScriptBinder            org.autojs.autoxjs.v7                D  action id = 4
2024-11-14 15:43:22.908  2204-9387  ScriptBinder            org.autojs.autoxjs.v7                D  engineName = com.stardust.autojs.script.JavaScriptSource.Engine
2024-11-14 15:43:22.909  2204-9387  JavaBinder              org.autojs.autoxjs.v7                E  *** Uncaught remote exception!  (Exceptions are not yet supported across processes.)
                                                                                                    java.io.FileNotFoundException: main.js (No such file or directory)
                                                                                                    	at java.io.FileInputStream.open0(Native Method)
                                                                                                    	at java.io.FileInputStream.open(FileInputStream.java:231)
                                                                                                    	at java.io.FileInputStream.<init>(FileInputStream.java:165)
                                                                                                    	at com.stardust.autojs.script.EncryptedScriptFileHeader.getHeaderFlags(EncryptedScriptFileHeader.kt:18)
                                                                                                    	at com.stardust.autojs.script.JavaScriptFileSource.parseExecutionMode(JavaScriptFileSource.kt:30)
                                                                                                    	at com.stardust.autojs.script.JavaScriptSource.getExecutionMode(JavaScriptSource.kt:27)
                                                                                                    	at com.stardust.autojs.ScriptEngineService.executeInternal(ScriptEngineService.kt:97)
                                                                                                    	at com.stardust.autojs.ScriptEngineService.execute(ScriptEngineService.kt:78)
                                                                                                    	at com.stardust.autojs.ScriptEngineService.execute(ScriptEngineService.kt:115)
                                                                                                    	at com.stardust.autojs.servicecomponents.ScriptBinder.runScript(ScriptBinder.kt:60)
                                                                                                    	at com.stardust.autojs.servicecomponents.ScriptBinder.access$runScript(ScriptBinder.kt:17)
                                                                                                    	at com.stardust.autojs.servicecomponents.ScriptBinder$onTransact$1.invokeSuspend(ScriptBinder.kt:25)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
                                                                                                    	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
                                                                                                    	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
                                                                                                    	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
                                                                                                    	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
                                                                                                    	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
                                                                                                    	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
                                                                                                    	at com.stardust.autojs.servicecomponents.ScriptBinder.onTransact(ScriptBinder.kt:20)
                                                                                                    	at android.os.Binder.execTransact(Binder.java:731)
```
10. 屏幕截图（可选）：

**Comment by aiselp** [comment]
需要有main字段指向入口文件，不然默认就是main.js

**Comment by zimoyin** [comment]
> 需要有main字段指向入口文件，不然默认就是main.js

我理解你的意思，但是很明显的是。该版本的APP 无法从当前项目所在的文件夹执行 main.js   

### 复现流程：  
使用 7.0.5 APP, 在APP 内使用APP 的新建项目功能。创建新项目后，无法通过项目中的运行按钮来运行   

![image](https://github.com/user-attachments/assets/dcec3db7-3965-4c58-9541-9012f0bc56b9)

----

该按钮可以运行代码  
![image](https://github.com/user-attachments/assets/a1687f7e-8494-471e-86e0-c4c01a38b4ba)

示例代码:  
main.js  
```js
toast(123)
```
project.json  

```json
{
  "abis": [
    "arm64-v8a",
    "armeabi-v7a",
    "x86",
    "x86_64"
  ],
  "assets": [],
  "buildDir": "build",
  "build": {
    "build_id": null,
    "build_number": 0,
    "build_time": 0
  },
  "useFeatures": [],
  "icon": null,
  "ignoredDirs": [],
  "encrypt-code": false,
  "launchConfig": {
    "displaySplash": true,
    "hideAccessibilityServices": false,
    "hideLauncher": false,
    "hideLogs": false,
    "stableMode": false,
    "volumeUpcontrol": false,
    "permissions": [],
    "serviceDesc": "使脚本自动操作(点击、长按、滑动等)所需，若关闭则只能执行不涉及自动操作的脚本。",
    "splashIcon": null,
    "splashText": "Powered by Autoxjs.com"
  },
  "libs": [],
  "main": "main.js",
  "name": "789",
  "outputPath": null,
  "packageName": "com.script.lgsxlh",
  "projectDirectory": null,
  "scripts": {},
  "signingConfig": {
    "alias": null,
    "keystore": null,
    "v1Sign": true,
    "v2Sign": true,
    "v3Sign": false,
    "v4Sign": false
  },
  "sourcePath": null,
  "useNodejs": false,
  "versionCode": 1,
  "versionName": "1"
}
```

综上：我认为这是一个BUG，该BUG无法在没有 sourcePath 字段的情况下正确的找到 main.js 。

**Comment by aiselp** [comment]
算是吧，project.json文件中我认为不应该储存sourcePath这种绝对路径字段

**Comment by tuyunlei** [comment]
我也遇到这个问题了，但是我即使指定了 `"sourcePath": "main.js"`，也还是无法运行 🤔

**Comment by zimoyin** [comment]
> sourcePath

sourcePath 是必须是绝对路径

**Comment by yejiu7411** [comment]
解决了吗

**Comment by wenfree** [comment]
是不能执行 有其它依赖的脚本

**Comment by wenfree** [comment]
他导入的文件在 sdcard/脚本/但是f5 执行的是在apk内部的路由地址. 所以你调不到相关的依赖文件, 就会报错啦. 所以你要写成 调试的时候默认为 sdcard/脚本/project为默认项目, 打包后就可以 files.cwd() 自动调用相关目录下的组件
