### ISSUE TITLE
RhinoJS、OpenCV模块更新及示例完善

### ISSUE THREAD

**Issue by Aioure** [kkevsekk1/AutoX#146]
尝试更新 RhinoJS 到1.7.13版，更新 opencv 到4.2.0版，改善7zip打包速度，添加多媒体、Webview扩展与游戏编程两组示例等，目前测试基本正常，但涉及到基础模块的改动，需要有更多更全面的测试才能保证可用性。建议可以发布为5.5.5，作为一个激进的版本，最好能多一些人参与测试完善。

**Comment by kkevsekk1** [comment]
图色查找，
No implementation found for long org.opencv.core.Mat.n_Mat() (tried Java_org_opencv_core_Mat_n_1Mat and Java_org_opencv_core_Mat_n_1Mat__)

**Comment by kkevsekk1** [comment]
升级opencv 后，基本改图，查颜色，等功能，爆出这个方法未实现

**Comment by kkevsekk1** [comment]
堆栈信息
java.lang.UnsatisfiedLinkError: No implementation found for long org.opencv.core.Mat.n_Mat() (tried Java_org_opencv_core_Mat_n_1Mat and Java_org_opencv_core_Mat_n_1Mat__)
	at org.opencv.core.Mat.n_Mat(Native Method)
	at org.opencv.core.Mat.<init>(Mat.java:23)
	at com.stardust.autojs.core.opencv.Mat.<init>(Mat.java:37)
	at com.stardust.autojs.core.image.ColorFinder.findColorInner(ColorFinder.java:76)
	at com.stardust.autojs.core.image.ColorFinder.findColor(ColorFinder.java:45)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:138)
	at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:226)
	at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1692)
	at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:1013)
	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:412)

**Comment by kkevsekk1** [comment]
你引用的 这个aar 没有 armeabi-v7a 他里面是 arm64-v8a

**Comment by Aioure** [comment]
> 升级opencv 后，基本改图，查颜色，等功能，爆出这个方法未实现

更新OpenCV到最新的4.5.5，修复图色查找bug。我这边测试正常，不知道你那边能不能运行？
