### ISSUE TITLE
574版本好像不能加载dex 运行会报错

### ISSUE THREAD

**Issue by nanmeng-sujin** [kkevsekk1/AutoX#213]
runtime.loadDex(path)
由于没有手机测试
不知是手机问题还是软件问题
大神看一下！麻烦了
还有一个问题是，打包的脚本打开后，授权储存权限时，提示需要授权才可以，授权完成后进不去，需要返回重进才可以进去

报错内容如下
11:54:28.420/E: No static method cmp_LT(Ljava/lang/Object;Ljava/lang/Object;)Z in class Lorg/mozilla/javascript/ScriptRuntime; or its super classes (declaration of 'org.mozilla.javascript.ScriptRuntime' appears in /data/app/org.autojs.autojs-jAzc9j3uD4GN5lSGjrGLYA==/base.apk!classes2.dex)

java.lang.NoSuchMethodError: No static method cmp_LT(Ljava/lang/Object;Ljava/lang/Object;)Z in class Lorg/mozilla/javascript/ScriptRuntime; or its super classes (declaration of 'org.mozilla.javascript.ScriptRuntime' appears in /data/app/org.autojs.autojs-jAzc9j3uD4GN5lSGjrGLYA==/base.apk!classes2.dex)
	at joy.wdBqMQR.6B5A6C7A5850575C7650660B(Unknown Source:137)
	at joy.wdBqMQR.call(Unknown Source:62)
	at org.mozilla.javascript.optimizer.OptRuntime.callName0(OptRuntime.java:66)
	at joy.wdBqMQR.6B5A6C4A53475D47446B09(Unknown Source:7)
	at joy.wdBqMQR.call(Unknown Source:22)
	at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1871)
	at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:1053)
	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:90)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:380)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3868)
	at org.mozilla.javascript.InterpretedFunction.exec(InterpretedFunction.java:103)
	at com.stardust.autojs.engine.RhinoJavaScriptEngine.doExecution(RhinoJavaScriptEngine.kt:76)
	at com.stardust.autojs.engine.JavaScriptEngine.execute(JavaScriptEngine.java:20)
	at com.stardust.autojs.engine.LoopBasedJavaScriptEngine.access$001(LoopBasedJavaScriptEngine.java:21)
	at com.stardust.autojs.engine.LoopBasedJavaScriptEngine.lambda$execute$0$LoopBasedJavaScriptEngine(LoopBasedJavaScriptEngine.java:46)
	at com.stardust.autojs.engine.-$$Lambda$LoopBasedJavaScriptEngine$jFbkAPP7Sh6djuubOT2CZQB_MAo.run(Unknown Source:6)
	at android.os.Handler.handleCallback(Handler.java:900)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:219)
	at com.stardust.autojs.engine.LoopBasedJavaScriptEngine.execute(LoopBasedJavaScriptEngine.java:65)
	at com.stardust.autojs.engine.LoopBasedJavaScriptEngine.execute(LoopBasedJavaScriptEngine.java:38)
	at com.stardust.autojs.execution.LoopedBasedJavaScriptExecution.doExecution(LoopedBasedJavaScriptExecution.java:42)
	at com.stardust.autojs.execution.RunnableScriptExecution.execute(RunnableScriptExecution.java:43)
	at com.stardust.autojs.execution.RunnableScriptExecution.execute(RunnableScriptExecution.java:37)
	at com.stardust.autojs.execution.RunnableScriptExecution.run(RunnableScriptExecution.java:31)
	at java.lang.Thread.run(Thread.java:929)

**Comment by admin0008** [comment]
同一个设备，换个低版本测试 就知道是不是这个版本的问题了

**Comment by nanmeng-sujin** [comment]
刚刚测试了一下，571不报错，572 574报错，因为没有573 也就是说自571之后都报错发自我的荣耀手机-------- 原始邮件 --------发件人： admin0008 ***@***.***>日期： 2022年2月15日周二 12:07收件人： kkevsekk1/AutoX ***@***.***>抄送： xichen ***@***.***>, Author ***@***.***>主    题： Re: [kkevsekk1/AutoX] 574版本好像不能加载dex 运行会报错 (Issue #213)

同一个设备，换个低版本测试 就知道是不是这个版本的问题了

**Comment by nanmeng-sujin** [comment]
> 

刚刚测试了一下，571不报错，572 574报错，因为没有573 也就是说自571之后都报错

**Comment by kkevsekk1** [comment]
先重启一下，在试试，或者是不是跟 rhino-1.7.14 有关系？

**Comment by syhyz** [comment]
> 先重启一下，在试试，或者是不是跟 rhino-1.7.14 有关系？

 @kkevsekk1 @admin0008 @nanmeng-sujin  rhino-1.7.14 用的gradle版本是7.2，会与gradle6编译的应用存在部分不兼容，建议试一下这个测试版[dev-test](https://github.com/syhyz/xxqg.auto.js) (gradle7.4编译的，同时修复打包问题) ，如果还是不行就说明rhino-1.7.14可能存在兼容性问题，可以考虑回退为rhino-1.7.13

**Comment by nanmeng-sujin** [comment]
重启了下，也不行，新版本575也是同样报错，至于上面提到的测试版，我这边没有条件进行编译测试，大佬们，你可以测试一下
