### ISSUE TITLE
使用的autoxjs 6.0.2 在小米11 ，安卓版本12上 执行 requestScreenCapture()时软件会直接崩溃，在华为手机上没有出现这个问题。

### ISSUE THREAD

**Issue by liwinl** [kkevsekk1/AutoX#246]
Version: 602
Android: 31
android.os.RemoteException: Remote stack trace:
	at com.android.server.media.projection.MediaProjectionManagerService$MediaProjection.start(MediaProjectionManagerService.java:553)
	at android.media.projection.IMediaProjection$Stub.onTransact(IMediaProjection.java:137)
	at android.os.Binder.execTransactInternal(Binder.java:1187)
	at android.os.Binder.execTransact(Binder.java:1146)

java.lang.RuntimeException:Failure delivering result ResultInfo{who=null, request=17777, result=-1, data=Intent { (has extras) }} to activity {org.autojs.autojs.dev/org.autojs.autojs.ui.main.MainActivity_}: java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.Set.add(java.lang.Object)' on a null object reference
android.app.ActivityThread.deliverResults(ActivityThread.java:5409)
......
Caused by:
android.os.RemoteException:Remote stack trace:
	at com.android.server.media.projection.MediaProjectionManagerService$MediaProjection.start(MediaProjectionManagerService.java:553)
	at android.media.projection.IMediaProjection$Stub.onTransact(IMediaProjection.java:137)
	at android.os.Binder.execTransactInternal(Binder.java:1187)
	at android.os.Binder.execTransact(Binder.java:1146)

**Comment by weili71** [comment]
android10以上录制屏幕需要使用前台服务，由于autox.js未适配。因此会出现崩溃

**Comment by diuchouni** [comment]
我也遇到这个问题。。望早点解决

**Comment by twinklelucas** [comment]
> android10以上录制屏幕需要使用前台服务，由于autox.js未适配。因此会出现崩溃

我的安卓11没什么问题

**Comment by Warm-rain** [comment]
同版本运行在红米k20pro miui12.5上无问题。

**Comment by wilinz** [comment]
> android10以上录制屏幕需要使用前台服务，由于autox.js未适配。因此会出现崩溃
Android 12 强制

**Comment by kkevsekk1** [comment]
估计权限问题



发送自我的盖乐世



-------- 原始信息 --------
发件人： "github-actions[bot]" ***@***.***>
日期: 2024/5/31 07:30 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： Subscribed ***@***.***>
主题： Re: [kkevsekk1/AutoX] 使用的autoxjs 6.0.2 在小米11 ，安卓版本12上 执行 requestScreenCapture()时软件会直接崩溃，在华为手机上没有出现这个问题。 (Issue #246)


此lssue由于长期未活动已被自动关闭，如问题任然存在，请重新打开lssue

―
