### ISSUE TITLE
运行ui老是报错 （Failed to define class）

### ISSUE THREAD

**Issue by diuchouni** [kkevsekk1/AutoX#254]
Failed to define classcom.stardust.autojs.rhino.AndroidClassLoader$FatalLoadingException: Failed to define class	at com.stardust.autojs.rhino.AndroidClassLoader.defineClass(AndroidClassLoader.java:70)	at org.mozilla.javascript.JavaAdapter.loadAdapterClass(JavaAdapter.java:535)	at org.mozilla.javascript.JavaAdapter.getAdapterClass(JavaAdapter.java:333)	at org.mozilla.javascript.JavaAdapter.js_createAdapter(JavaAdapter.java:173)	at org.mozilla.javascript.JavaAdapter.execIdCall(JavaAdapter.java:86)	at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:101)	at org.mozilla.javascript.BaseFunction.construct(BaseFunction.java:364)	at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1525)	at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:815)	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109)	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:399)	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3452)	at org.mozilla.javascript.InterpretedFunction.exec(InterpretedFunction.java:120)	at com.stardust.autojs.engine.RhinoJavaScriptEngine.doExecution(RhinoJavaScriptEngine.kt:76)	at com.stardust.autojs.engine.JavaScriptEngine.execute(JavaScriptEngine.java:20)	at com.stardust.autojs.engine.LoopBasedJavaScriptEngine.access$001(LoopBasedJavaScriptEngine.java:21)	at com.stardust.autojs.engine.LoopBasedJavaScriptEngine.lambda$execute$0$LoopBasedJavaScriptEngine(LoopBasedJavaScriptEngine.java:46)	at com.stardust.autojs.engine.-$$Lambda$LoopBasedJavaScriptEngine$jFbkAPP7Sh6djuubOT2CZQB_MAo.run(Unknown Source:6)	at android.os.Handler.handleCallback(Handler.java:794)	at android.os.Handler.dispatchMessage(Handler.java:99)	at android.os.Looper.loop(Looper.java:176)	at android.app.ActivityThread.main(ActivityThread.java:6662)	at java.lang.reflect.Method.invoke(Native Method)	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)Caused by: java.lang.ClassNotFoundException: Didn't find class "adapter1" on path: DexPathList[[zip file "/data/user/0/com.laoheiaj/cache/classes/1648363908326.jar"],nativeLibraryDirectories=[/system/lib, /vendor/lib]]	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)	at com.stardust.autojs.rhino.AndroidClassLoader.defineClass(AndroidClassLoader.java:68)	... 24 more	Suppressed: java.io.IOException: No original dex files found for dex location /data/user/0/com.laoheiaj/cache/classes/1648363908326.jar		at dalvik.system.DexFile.openDexFileNative(Native Method)		at dalvik.system.DexFile.openDexFile(DexFile.java:353)		at dalvik.system.DexFile.<init>(DexFile.java:100)		at dalvik.system.DexFile.<init>(DexFile.java:74)		at dalvik.system.DexPathList.loadDexFile(DexPathList.java:374)		at dalvik.system.DexPathList.makeDexElements(DexPathList.java:337)		at dalvik.system.DexPathList.<init>(DexPathList.java:157)		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:65)		at dalvik.system.DexClassLoader.<init>(DexClassLoader.java:54)		at com.stardust.autojs.rhino.AndroidClassLoader.loadDex(AndroidClassLoader.java:130)		at com.stardust.autojs.rhino.AndroidClassLoader.dexJar(AndroidClassLoader.java:145)		... 25 more

**Comment by diuchouni** [comment]
要停止运行autoxjs 才可以！很烦
