### ISSUE TITLE
[BUG]6.0.8打包后ppocr无法识别出文本，或者卡住

### ISSUE THREAD

**Issue by wangwang-code** [kkevsekk1/AutoX#287]
![Screenshot_20220529_210906](https://user-images.githubusercontent.com/64469117/170870476-bab8f225-b6f2-4419-abe5-52a05b695089.jpg)
@kkevsekk1 @wilinz @LZX284
修🐛了

**Comment by wangwang-code** [comment]
打包的是示例-AI-PaddleOCR.js
这是不打包的直接运行的 
![Screenshot_20220529_211808](https://user-images.githubusercontent.com/64469117/170870803-674e144d-ed4d-478a-a0e3-a5a80b89aa60.jpg)

**Comment by wilinz** [comment]
勾选OCR了没？

**Comment by wilinz** [comment]
> 打包的是示例-AI-PaddleOCR.js 这是不打包的直接运行的 ![Screenshot_20220529_211808](https://user-images.githubusercontent.com/64469117/170870803-674e144d-ed4d-478a-a0e3-a5a80b89aa60.jpg)

勾选OCR了没
![Screenshot_2022-05-29-21-24-38-308_org autojs autojs dev](https://user-images.githubusercontent.com/59408438/170871143-2af29c5e-2c21-49e6-bcdf-c49f6131d90b.png)

**Comment by wangwang-code** [comment]
> 勾选OCR了没？

100%勾选了 apk大小27M以上

**Comment by wilinz** [comment]
> > 勾选OCR了没？
> 
> 100%勾选了 apk大小27M以上

这个就不懂了， 让@LZX284看看，升级的OCR可能有问题，我没时间最近

**Comment by wangwang-code** [comment]
![Screenshot_20220529_212607](https://user-images.githubusercontent.com/64469117/170871212-dc1085f9-d14d-4c03-bc29-1ccfeebd8352.jpg)

请不要把我当成不检查编译配置就发issue的，改问题在老版 http://file.ar01.cn/appstore/app/20220301141633.apk 中未出过 推测是升级ocr出幺蛾子了

**Comment by wangwang-code** [comment]
> 

@LZX284

**Comment by wilinz** [comment]
旧版本没问题吧

**Comment by wangwang-code** [comment]
> 旧版本没问题吧

对

**Comment by wilinz** [comment]
> > 旧版本没问题吧
> 
> 对

6.0.6和6.0.7试过没

**Comment by LZX284** [comment]
@wangwang-code  你是自己编译的吗？是的话，把 autojs这个模块build.gradle里的PaddleOCR4Android依赖库版本升级成1.0.1试试
@wilinz 不知道为什么，华为手机上打包的应用无法安装，提示“与操作系统不兼容”，所以我这边无法测试修改后的效果

**Comment by wilinz** [comment]
> @wangwang-code 你是自己编译的吗？是的话，把 autojs这个模块build.gradle里的PaddleOCR4Android依赖库版本升级成1.0.1试试 @wilinz 不知道为什么，华为手机上打包的应用无法安装，提示“与操作系统不兼容”，所以我这边无法测试修改后的效果

鸿蒙系统吗

**Comment by wangwang-code** [comment]
> @wangwang-code 你是自己编译的吗？是的话，把 autojs这个模块build.gradle里的PaddleOCR4Android依赖库版本升级成1.0.1试试 @wilinz 不知道为什么，华为手机上打包的应用无法安装，提示“与操作系统不兼容”，所以我这边无法测试打包应用的效果

确实我复制了一个分支，并正常用github打包了，但要22分钟，我22点就要睡了，测试不了

**Comment by wangwang-code** [comment]
> 

https://github.com/wangwang-code/AutoX 

在编译了

**Comment by LZX284** [comment]
> 鸿蒙系统吗

是的

**Comment by wangwang-code** [comment]
@wilinz  @LZX284  测试只能留给二位了

**Comment by wilinz** [comment]
> > 鸿蒙系统吗
> 
> 是的

应该是有兼容性问题，试试换一下签名

**Comment by wangwang-code** [comment]
(原本复制分支构建，是想把确定和输入框砍掉的

**Comment by LZX284** [comment]
> > > 鸿蒙系统吗
> > 
> > 
> > 是的
> 
> 应该是有兼容性问题，试试换一下签名

签名有什么要注意的地方吗？换了自己的签名，还是提示“应用是非正式发布版本，当前设备不支持安装”，

**Comment by wangwang-code** [comment]
> > > > 鸿蒙系统吗
> > > 
> > > 
> > > 是的
> > 
> > 
> > 应该是有兼容性问题，试试换一下签名
> 
> 签名有什么要注意的地方吗？换了自己的签名，还是提示“应用是非正式发布版本，当前设备不支持安装”，

能装vmos的话，那就套一层运行

**Comment by LZX284** [comment]
> 确实我复制了一个分支，并正常用github打包了，但要22分钟，我22点就要睡了，测试不了

如果不是急用的话，那明天或后天应该也可以吧

**Comment by wilinz** [comment]
> > > > 鸿蒙系统吗
> > > 
> > > 
> > > 是的
> > 
> > 
> > 应该是有兼容性问题，试试换一下签名
> 
> 签名有什么要注意的地方吗？换了自己的签名，还是提示“应用是非正式发布版本，当前设备不支持安装”，

可能template apk是debug版本

**Comment by wangwang-code** [comment]
> > 确实我复制了一个分支，并正常用github打包了，但要22分钟，我22点就要睡了，测试不了
> 
> 如果不是急用的话，那明天或后天应该也可以吧

我不急，但其他用我打包出来就不清楚了

**Comment by wangwang-code** [comment]
https://github.com/wangwang-code/AutoX/runs/6643675020?check_suite_focus=true 还有10分钟就好了

**Comment by LZX284** [comment]
> template apk是debug版本

> 我不急，但其他用我打包出来就不清楚了

template apk换成release版后可以安装了，但这边的测试结果依然不行，不知道是否opencv版本的关系，打包的话暂时还是用6.0.6版的吧

**Comment by LZX284** [comment]
@wilinz OCR在应用中测试没问题，不知道打包后的环境和应用中的主要有什么差别？OCR一般在模型加载失败时结果才为空，但为了解决这个问题，先前已经加入了初始化校验，加载失败的可能性应该说是很低了，但测试时打包的OCR几乎就没有成功过，不知道是不是环境依赖上出了什么差错？

**Comment by wilinz** [comment]
> @wilinz OCR在应用中测试没问题，不知道打包后的环境和应用中的主要有什么差别？OCR一般在模型加载失败时结果才为空，但为了解决这个问题，先前已经加入了初始化校验，加载失败的可能性应该说是很低了，但测试时打包的OCR几乎就没有成功过，不知道是不是环境依赖上出了什么差错？

等我调试看看

**Comment by LZX284** [comment]
> 等我调试看看

@wilinz 这个示例是对当前目录下的图片进行识别的，不知道打包时能不能保证把同目录下所有文件都打包进去，如果不能，识别结果自然就只能为空了……

**Comment by wilinz** [comment]
> > 等我调试看看
> 
> @wilinz 这个示例是对当前目录下的图片进行识别的，不知道打包时能不能保证把同目录下所有文件都打包进去？如果不能，识别结果就可能会出错

录屏的也不得捏

**Comment by LZX284** [comment]
> 录屏的也不得捏
 
录屏的那个，显示的检测时间是正常的（至少都用了一点几秒），只是没法画出检测结果（估计是UI方面的问题），你在录屏里面加一句toastLog显示结果，或是在打包的应用里加上必要的图片，应该就能看出是不是OCR本身出了问题

**Comment by wilinz** [comment]
2022-05-29 23:39:26.729 9159-9237/? D/GlobalConsole: 23:39:26.729/V: 开始运行[main.js]
2022-05-29 23:39:26.746 9159-9237/? I/Predictor: Word label size: 6624
2022-05-29 23:39:26.746 9159-9237/? I/Predictor: realPath.isEmpty() /data/user/0/com.example.script1653835558649/cache/models/ocr_v2_for_cpu(slim)
2022-05-29 23:39:26.779 9159-9237/? I/Predictor: model path/data/user/0/com.example.script1653835558649/cache/models/ocr_v2_for_cpu(slim)/ch_ppocr_mobile_v2.0_det_opt.nb ; /data/user/0/com.example.script1653835558649/cache/models/ocr_v2_for_cpu(slim)/ch_ppocr_mobile_v2.0_rec_opt.nb;/data/user/0/com.example.script1653835558649/cache/models/ocr_v2_for_cpu(slim)/ch_ppocr_mobile_v2.0_cls_opt.nb
2022-05-29 23:39:26.801 9159-9237/? E/pt165383555864: No implementation found for long cn.android.ocr.OCRPredictorNative.init(java.lang.String, java.lang.String, java.lang.String, int, java.lang.String) (tried Java_cn_android_ocr_OCRPredictorNative_init and Java_cn_android_ocr_OCRPredictorNative_init__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2ILjava_lang_String_2)
2022-05-29 23:39:26.802 9159-9237/? W/System.err: java.lang.UnsatisfiedLinkError: No implementation found for long cn.android.ocr.OCRPredictorNative.init(java.lang.String, java.lang.String, java.lang.String, int, java.lang.String) (tried Java_cn_android_ocr_OCRPredictorNative_init and Java_cn_android_ocr_OCRPredictorNative_init__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2ILjava_lang_String_2)
2022-05-29 23:39:26.802 9159-9237/? W/System.err:     at cn.android.ocr.OCRPredictorNative.init(Native Method)
2022-05-29 23:39:26.802 9159-9237/? W/System.err:     at cn.android.ocr.OCRPredictorNative.<init>(OCRPredictorNative.java:35)
2022-05-29 23:39:26.802 9159-9237/? W/System.err:     at cn.android.ocr.Predictor.loadModel(Predictor.java:141)
2022-05-29 23:39:26.802 9159-9237/? W/System.err:     at cn.android.ocr.Predictor.initOcr(Predictor.java:395)
2022-05-29 23:39:26.802 9159-9237/? W/System.err:     at com.stardust.autojs.runtime.api.Paddle.initOcr(Paddle.java:27)
2022-05-29 23:39:26.802 9159-9237/? W/System.err:     at com.stardust.autojs.runtime.api.Paddle.ocr(Paddle.java:41)
2022-05-29 23:39:26.802 9159-9237/? W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2022-05-29 23:39:26.802 9159-9237/? W/System.err:     at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:138)
2022-05-29 23:39:26.802 9159-9237/? W/System.err:     at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:226)
2022-05-29 23:39:26.802 9159-9237/? W/System.err:     at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1692)
2022-05-29 23:39:26.802 9159-9237/? W/System.err:     at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:1013)
2022-05-29 23:39:26.802 9159-9237/? W/System.err:     at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109)
2022-05-29 23:39:26.802 9159-9237/? W/System.err:     at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:412)
2022-05-29 23:39:26.802 9159-9237/? W/System.err:     at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3578)
2022-05-29 23:39:26.802 9159-9237/? W/System.err:     at org.mozilla.javascript.InterpretedFunction.exec(InterpretedFunction.java:121)
2022-05-29 23:39:26.802 9159-9237/? W/System.err:     at com.stardust.autojs.engine.RhinoJavaScriptEngine.doExecution(RhinoJavaScriptEngine.kt:76)
2022-05-29 23:39:26.802 9159-9237/? W/System.err:     at com.stardust.autojs.engine.JavaScriptEngine.execute(JavaScriptEngine.java:20)
2022-05-29 23:39:26.802 9159-9237/? W/System.err:     at com.stardust.autojs.engine.LoopBasedJavaScriptEngine.access$001(LoopBasedJavaScriptEngine.java:21)
2022-05-29 23:39:26.802 9159-9237/? W/System.err:     at com.stardust.autojs.engine.LoopBasedJavaScriptEngine.lambda$execute$0$com-stardust-autojs-engine-LoopBasedJavaScriptEngine(LoopBasedJavaScriptEngine.java:46)
2022-05-29 23:39:26.802 9159-9237/? W/System.err:     at com.stardust.autojs.engine.LoopBasedJavaScriptEngine$$ExternalSyntheticLambda0.run(Unknown Source:6)
2022-05-29 23:39:26.802 9159-9237/? W/System.err:     at android.os.Handler.handleCallback(Handler.java:914)
2022-05-29 23:39:26.802 9159-9237/? W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:100)
2022-05-29 23:39:26.802 9159-9237/? W/System.err:     at android.os.Looper.loop(Looper.java:228)
2022-05-29 23:39:26.802 9159-9237/? W/System.err:     at com.stardust.autojs.engine.LoopBasedJavaScriptEngine.execute(LoopBasedJavaScriptEngine.java:65)
2022-05-29 23:39:26.802 9159-9237/? W/System.err:     at com.stardust.auojs.inrt.autojs.XJavaScriptEngine.execute(XJavaScriptEngine.kt:28)
2022-05-29 23:39:26.802 9159-9237/? W/System.err:     at com.stardust.autojs.engine.LoopBasedJavaScriptEngine.execute(LoopBasedJavaScriptEngine.java:38)
2022-05-29 23:39:26.802 9159-9237/? W/System.err:     at com.stardust.auojs.inrt.autojs.XJavaScriptEngine.execute(XJavaScriptEngine.kt:37)
2022-05-29 23:39:26.802 9159-9237/? W/System.err:     at com.stardust.auojs.inrt.autojs.XJavaScriptEngine.execute(XJavaScriptEngine.kt:20)
2022-05-29 23:39:26.802 9159-9237/? W/System.err:     at com.stardust.autojs.engine.LoopBasedJavaScriptEngine.execute(LoopBasedJavaScriptEngine.java:38)
2022-05-29 23:39:26.803 9159-9237/? W/System.err:     at com.stardust.autojs.execution.LoopedBasedJavaScriptExecution.doExecution(LoopedBasedJavaScriptExecution.java:42)
2022-05-29 23:39:26.803 9159-9237/? W/System.err:     at com.stardust.autojs.execution.RunnableScriptExecution.execute(RunnableScriptExecution.java:43)
2022-05-29 23:39:26.803 9159-9237/? W/System.err:     at com.stardust.autojs.execution.RunnableScriptExecution.execute(RunnableScriptExecution.java:37)
2022-05-29 23:39:26.803 9159-9237/? W/System.err:     at com.stardust.autojs.execution.RunnableScriptExecution.run(RunnableScriptExecution.java:31)
2022-05-29 23:39:26.803 9159-9237/? W/System.err:     at java.lang.Thread.run(Thread.java:919)
2022-05-29 23:39:26.803 9159-9237/? D/GlobalConsole: 23:39:26.803/V: 
    ------------
    [main.js]运行结束，用时0.073000秒

**Comment by wilinz** [comment]
初始化出现问题

**Comment by LZX284** [comment]
> 初始化出现问题

@wilinz  6.0.6版没有打包图片的话，ocr识别结果也会为空。6.0.8有点奇怪，根据调试显示的情况，加载so库是成功的，但却说找不到so库中的方法，同时在app中调用却有没问题，是不是可能有些和so库相关的依赖关系是打包中所缺少的或是被混淆了？
