### ISSUE TITLE
程序总是奇怪退出

### ISSUE THREAD

**Issue by majin78** [kkevsekk1/AutoX#301]
RT,我脚本运行的时候发现总是有运行到中途的时候莫名退出。
我后来通过打日志的方式去追逐，发现调用 back()的时候很大概率会把整个autojsx的程序退出。
运行的是在平板鸿蒙OS上，有开启悬浮窗，请问大家有遇到过这个问题吗？
有什么方式能追踪吗？

[Extension Host] close: device = Device HUAWEI SCM-AL09(192.168.1.181), reason = 1006, desc = Connection dropped by remote peer.
workbench.desktop.main.js:71 [Extension Host] detachDevice: HUAWEI SCM-AL09[Disconnected]
workbench.desktop.main.js:2670 [[object Object]]Cannot read properties of undefined (reading 'appendLine')
$onExtensionRuntimeError @ workbench.desktop.main.js:2670
_doInvokeHandler @ workbench.desktop.main.js:1719
_invokeHandler @ workbench.desktop.main.js:1719
_receiveRequest @ workbench.desktop.main.js:1719
_receiveOneMessage @ workbench.desktop.main.js:1719
（匿名） @ workbench.desktop.main.js:1719
invoke @ workbench.desktop.main.js:67
deliver @ workbench.desktop.main.js:67
fire @ workbench.desktop.main.js:67
fire @ workbench.desktop.main.js:83
_receiveMessage @ workbench.desktop.main.js:83
（匿名） @ workbench.desktop.main.js:83
invoke @ workbench.desktop.main.js:67
deliver @ workbench.desktop.main.js:67
fire @ workbench.desktop.main.js:67
acceptChunk @ workbench.desktop.main.js:83
（匿名） @ workbench.desktop.main.js:83
O @ workbench.desktop.main.js:3170
emit @ node:events:390
addChunk @ node:internal/streams/readable:315
readableAddChunk @ node:internal/streams/readable:289
Readable.push @ node:internal/streams/readable:228
onStreamRead @ node:internal/stream_base_commons:199
workbench.desktop.main.js:2670 TypeError: Cannot read properties of undefined (reading 'appendLine')
	at AutoJsDebugServer.detachDevice (c:\Users\Administrator\.vscode\extensions\aaroncheng.auto-js-vsce-fixed-1.101.0\out\autojs-debug.js:255:35)
	at Device.emit (node:events:390:28)
	at WebSocketConnection.<anonymous> (c:\Users\Administrator\.vscode\extensions\aaroncheng.auto-js-vsce-fixed-1.101.0\out\autojs-debug.js:100:18)
	at WebSocketConnection.emit (node:events:402:35)
	at WebSocketConnection.handleSocketClose (c:\Users\Administrator\.vscode\extensions\aaroncheng.auto-js-vsce-fixed-1.101.0\node_modules\websocket\lib\WebSocketConnection.js:387:14)
	at Socket.emit (node:events:390:28)
	at TCP.<anonymous> (node:net:687:12)

**Comment by LZX284** [comment]
@majin78  是只有一个脚本会这样还是很多脚本都有这个问题？追踪问题可以通过Android Studio调试，但也需要有具体代码，要不没法搞得……

**Comment by Clierbin** [comment]
我也是  辛苦作者看下
