### ISSUE TITLE
雷电模拟器32位版本 测试设置4核CPU以下使用AI识别会崩溃,4核及以上可以正常使用

### ISSUE THREAD

**Issue by gaokui2010** [kkevsekk1/AutoX#373]
**版本号:autojsx[dev] 6.2.3 app-dev-arm64-v8a-release-unsigned-signed.apk**
11:29:19.545/E: No implementation found for long com.baidu.paddle.lite.demo.ocr.OCRPredictorNative.init(java.lang.String, java.lang.String, java.lang.String, int, java.lang.String) (tried Java_com_baidu_paddle_lite_demo_ocr_OCRPredictorNative_init and Java_com_baidu_paddle_lite_demo_ocr_OCRPredictorNative_init__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2ILjava_lang_String_2)

java.lang.UnsatisfiedLinkError: No implementation found for long com.baidu.paddle.lite.demo.ocr.OCRPredictorNative.init(java.lang.String, java.lang.String, java.lang.String, int, java.lang.String) (tried Java_com_baidu_paddle_lite_demo_ocr_OCRPredictorNative_init and Java_com_baidu_paddle_lite_demo_ocr_OCRPredictorNative_init__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2ILjava_lang_String_2)
	at com.baidu.paddle.lite.demo.ocr.OCRPredictorNative.init(Native Method)
	at com.baidu.paddle.lite.demo.ocr.OCRPredictorNative.<init>(OCRPredictorNative.java:33)
	at com.baidu.paddle.lite.demo.ocr.Predictor.loadModel(Predictor.java:135)
	at com.baidu.paddle.lite.demo.ocr.Predictor.initOcr(Predictor.java:388)
	at com.stardust.autojs.runtime.api.Paddle.initOcr(Paddle.java:19)
	at com.stardust.autojs.runtime.api.Paddle.ocr(Paddle.java:35)
	at com.stardust.autojs.runtime.api.Paddle.ocr(Paddle.java:59)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:206)
	at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:211)
	at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1879)
	at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:1061)
	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:90)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:380)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3869)
	at org.mozilla.javascript.InterpretedFunction.exec(InterpretedFunction.java:103)
	at com.stardust.autojs.engine.RhinoJavaScriptEngine.doExecution(RhinoJavaScriptEngine.kt:76)
	at com.stardust.autojs.engine.JavaScriptEngine.execute(JavaScriptEngine.java:20)
	at com.stardust.autojs.engine.LoopBasedJavaScriptEngine.access$001(LoopBasedJavaScriptEngine.java:21)
	at com.stardust.autojs.engine.LoopBasedJavaScriptEngine.lambda$execute$0$com-stardust-autojs-engine-LoopBasedJavaScriptEngine(LoopBasedJavaScriptEngine.java:46)
	at com.stardust.autojs.engine.LoopBasedJavaScriptEngine$$ExternalSyntheticLambda0.run(D8$$SyntheticClass)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at com.stardust.autojs.engine.LoopBasedJavaScriptEngine.execute(LoopBasedJavaScriptEngine.java:65)
	at com.stardust.autojs.engine.LoopBasedJavaScriptEngine.execute(LoopBasedJavaScriptEngine.java:38)
	at com.stardust.autojs.execution.LoopedBasedJavaScriptExecution.doExecution(LoopedBasedJavaScriptExecution.java:42)
	at com.stardust.autojs.execution.RunnableScriptExecution.execute(RunnableScriptExecution.java:43)
	at com.stardust.autojs.execution.RunnableScriptExecution.execute(RunnableScriptExecution.java:37)
	at com.stardust.autojs.execution.RunnableScriptExecution.run(RunnableScriptExecution.java:31)
	at java.lang.Thread.run(Thread.java:761)

**Comment by kkevsekk1** [comment]
没有具体的实现……



发送自我的盖乐世



-------- 原始信息 --------
发件人： gaokui2010 ***@***.***>
日期: 2022/7/21 11:50 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： Subscribed ***@***.***>
主题： [kkevsekk1/AutoX] 雷电模拟器32位版本 测试设置4核CPU以下使用AI识别会崩溃,4核及以上可以正常使用 (Issue #373)


版本号:autojsx[dev] 6.2.3 app-dev-arm64-v8a-release-unsigned-signed.apk
11:29:19.545/E: No implementation found for long com.baidu.paddle.lite.demo.ocr.OCRPredictorNative.init(java.lang.String, java.lang.String, java.lang.String, int, java.lang.String) (tried Java_com_baidu_paddle_lite_demo_ocr_OCRPredictorNative_init and Java_com_baidu_paddle_lite_demo_ocr_OCRPredictorNative_init__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2ILjava_lang_String_2)

java.lang.UnsatisfiedLinkError: No implementation found for long com.baidu.paddle.lite.demo.ocr.OCRPredictorNative.init(java.lang.String, java.lang.String, java.lang.String, int, java.lang.String) (tried Java_com_baidu_paddle_lite_demo_ocr_OCRPredictorNative_init and Java_com_baidu_paddle_lite_demo_ocr_OCRPredictorNative_init__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2ILjava_lang_String_2)
at com.baidu.paddle.lite.demo.ocr.OCRPredictorNative.init(Native Method)
at com.baidu.paddle.lite.demo.ocr.OCRPredictorNative.(OCRPredictorNative.java:33)
at com.baidu.paddle.lite.demo.ocr.Predictor.loadModel(Predictor.java:135)
at com.baidu.paddle.lite.demo.ocr.Predictor.initOcr(Predictor.java:388)
at com.stardust.autojs.runtime.api.Paddle.initOcr(Paddle.java:19)
at com.stardust.autojs.runtime.api.Paddle.ocr(Paddle.java:35)
at com.stardust.autojs.runtime.api.Paddle.ocr(Paddle.java:59)
at java.lang.reflect.Method.invoke(Native Method)
at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:206)
at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:211)
at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1879)
at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:1061)
at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:90)
at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:380)
at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3869)
at org.mozilla.javascript.InterpretedFunction.exec(InterpretedFunction.java:103)
at com.stardust.autojs.engine.RhinoJavaScriptEngine.doExecution(RhinoJavaScriptEngine.kt:76)
at com.stardust.autojs.engine.JavaScriptEngine.execute(JavaScriptEngine.java:20)
at com.stardust.autojs.engine.LoopBasedJavaScriptEngine.access$001(LoopBasedJavaScriptEngine.java:21)
at com.stardust.autojs.engine.LoopBasedJavaScriptEngine.lambda$execute$0$com-stardust-autojs-engine-LoopBasedJavaScriptEngine(LoopBasedJavaScriptEngine.java:46)
at com.stardust.autojs.engine.LoopBasedJavaScriptEngine$$ExternalSyntheticLambda0.run(D8$$SyntheticClass)
at android.os.Handler.handleCallback(Handler.java:751)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:154)
at com.stardust.autojs.engine.LoopBasedJavaScriptEngine.execute(LoopBasedJavaScriptEngine.java:65)
at com.stardust.autojs.engine.LoopBasedJavaScriptEngine.execute(LoopBasedJavaScriptEngine.java:38)
at com.stardust.autojs.execution.LoopedBasedJavaScriptExecution.doExecution(LoopedBasedJavaScriptExecution.java:42)
at com.stardust.autojs.execution.RunnableScriptExecution.execute(RunnableScriptExecution.java:43)
at com.stardust.autojs.execution.RunnableScriptExecution.execute(RunnableScriptExecution.java:37)
at com.stardust.autojs.execution.RunnableScriptExecution.run(RunnableScriptExecution.java:31)
at java.lang.Thread.run(Thread.java:761)

―

**Comment by LZX284** [comment]
@gaokui2010  PaddleOCR升级到3.5办了(提升识别速度及准确率)，你看看效果如何：
[Auto.Js+ V6.2.5](https://github.com/LZX284/Auto.Js/releases/tag/6.2.5)

**Comment by gaokui2010** [comment]
@LZX284 感谢,但是经测试,依旧有此问题

**Comment by gaokui2010** [comment]
我尝试更换了其他模拟器(逍遥,夜神),也是无法正常使用

**Comment by LZX284** [comment]
> @LZX284 感谢,但是经测试,依旧有此问题

@gaokui2010 那这个问题就是飞浆自身架构兼容性不足了，其实可以的话还是建议CPU设置4核及使用64位模拟器，这样不仅是OCR，连APP本身及其它Native模块性能表现也会好很多

**Comment by yangy996** [comment]
可以尝试这个，效果还可以
https://blog.csdn.net/YY007H/article/details/124540297

**Comment by ShiverZm** [comment]
也有可能是安装的架构apk有问题，试试用unversal版本的apk
