### ISSUE TITLE
`http.get`方法没有默认从WLAN连接导致超时

### ISSUE THREAD

**Issue by Pil0tXia** [kkevsekk1/AutoX#464]
1. Autox.js 版本：635
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 12
4. Android 机型：红米K40
5. Android 系统类别：MIUI 13.0.7
6. 问题描述：我写了一个校园网自动登录的脚本，在华为P30上运行良好，但是在红米K40上会报无法连接、连接超时的错误。关闭系统流量之后，脚本就可以正常工作了。开启系统流量和WLAN时，浏览器可以打开a.nuist.edu.cn（校园网认证登录页的url），但打不开10.255.255.34（校园网认证登录页的ip），显然是请求指向了流量的内网。但是禁用autox.js的流量使用权限、只能连接WLAN后，脚本会直接报错，跳过了Timeout的时间。把脚本里的两处ip改为a.nuist.edu.cn也是一样。请问可否从软件或代码上限制`http.get`方法从WLAN连接？
7. 脚本：
```
// 填写账户信息
var username = ""
var password = ""
var ISP = "移动"

// ----------------------------------------------------------------
toastLog("正在启动...");
var dict = { "移动": "2", "电信": "3", "联通": "4" }
var channel = dict[ISP]
var ip_url = "http://10.255.255.34/api/v1/ip"
var login_url = "http://10.255.255.34/api/v1/login"

var resp = http.get(ip_url);
var result = resp.body.json()
if (result.code != 200) {
    toastLog(`登录失败！\n错误信息: ${result.message}`);
} else {
    var ip = result.data;
    var resp = http.postJson(login_url, {
        username: username,
        password: password,
        channel: channel,
        usripadd: ip,
        pagesign: "secondauth",
        ifautologin: "0",
    });
    var result = resp.body.json()
    if (result.code != 200) {
        toastLog(`登录失败！\n错误信息: ${result.message}`);
    } else {
        toastLog(`登录成功！\n用户: ${username}\nIP: ${ip}`);
    }
}
```
8. 报错日志：
```
22:55:01.063/D: 正在启动...
22:55:01.066/E: Wrapped java.net.ConnectException: Failed to connect to /10.255.255.34:80 (file:///android_asset/modules/__http__.js#49)
Wrapped java.net.ConnectException: Failed to connect to /10.255.255.34:80
at file:///android_asset/modules/__http__.js:49:0
at /storage/emulated/0/脚本/login.js:13:0
```

**Comment by Pil0tXia** [comment]
@WangJerry1229 我目前对这个issue没有需求了，所以没有继续关注了。你可以联系开发者@kkevsekk1 和@aiselp 来协助解决此问题。

**Comment by Pil0tXia** [comment]
@kkevsekk1 这个stale bot设置的不合理，第一次添加stale标签的时候应该留下comment，否则参与者收不到任何通知。
