### ISSUE TITLE
ui模式使用confirm报错

### ISSUE THREAD

**Issue by LYS86** [kkevsekk1/AutoX#519]
1. Autox.js 版本：636
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 10
4. Android 机型：小米10
5. Android 系统类别：MIUI
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：
9. 运行以下代码报错，去掉ui正常
10. 'ui';

 confirm("要清除所有缓存吗?",null, function (clear) {
  if (clear) {
    alert("清除成功!");
  }
});
11. 报错日志（可选）：
12. 17:38:27.508/E: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter r

java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter r
	at com.stardust.autojs.execution.ScriptExecuteActivity$doExecution$1.onResult(Unknown Source:2)
	at com.stardust.autojs.engine.LoopBasedJavaScriptEngine.lambda$execute$0$com-stardust-autojs-engine-LoopBasedJavaScriptEngine(LoopBasedJavaScriptEngine.java:48)
	at com.stardust.autojs.engine.LoopBasedJavaScriptEngine$$ExternalSyntheticLambda0.run(Unknown Source:6)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8293)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
13. 屏幕截图（可选）：

**Comment by kkevsekk1** [comment]
有模态框；这玩意是js代码运行在java里，和js运行在v8里，和js运行在node里不是同一个东西，



发送自我的盖乐世



-------- 原始信息 --------
发件人： LYS ***@***.***>
日期: 2023/3/13 17:42 (GMT+08:00)
收件人： kkevsekk1/AutoX ***@***.***>
抄送： Subscribed ***@***.***>
主题： [kkevsekk1/AutoX] ui模式使用confirm报错 (Issue #519)


  1.  Autox.js 版本：636
  2.  Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
  3.  Android 版本：Android 10
  4.  Android 机型：小米10
  5.  Android 系统类别：MIUI
  6.  VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
  7.  问题描述：
  8.  运行以下代码报错，去掉ui正常
  9.  'ui';

confirm("要清除所有缓存吗?",null, function (clear) {
  if (clear) {
    alert("清除成功!");
  }
});
11. 报错日志（可选）：
12. 17:38:27.508/E: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter r

java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter r
at com.stardust.autojs.execution.ScriptExecuteActivity$doExecution$1.onResult(Unknown Source:2)
at com.stardust.autojs.engine.LoopBasedJavaScriptEngine.lambda$execute$0$com-stardust-autojs-engine-LoopBasedJavaScriptEngine(LoopBasedJavaScriptEngine.java:48)
at com.stardust.autojs.engine.LoopBasedJavaScriptEngine$$ExternalSyntheticLambda0.run(Unknown Source:6)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:210)
at android.os.Looper.loop(Looper.java:299)
at android.app.ActivityThread.main(ActivityThread.java:8293)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
13. 屏幕截图（可选）：

―

**Comment by LYS86** [comment]
文档指明对话框使用回调函数或者Promise的形式，经测试，ui模式使用回调只有build，input正常使用，其他函数都报这个错，Promise可以使用

**Comment by LYS86** [comment]
这个示例报错，
![e69171c8c4cb962636039b2cb1fbd3e](https://user-images.githubusercontent.com/106499400/224876393-2b10803a-d774-4cfb-854a-6ed85113ea85.png)
![64e1295f34b4c66489feb5b038eb371](https://user-images.githubusercontent.com/106499400/224876414-b0afa9d7-c5a9-47df-ae7f-70342846bd78.png)
