### ISSUE TITLE
642 Attempt to read from field 'org.mozilla.javascript.Scriptable org.mozilla.javascript.Context.topCallScope' on a null object reference

### ISSUE THREAD

**Issue by lanmingle** [kkevsekk1/AutoX#593]
1. Autox.js 版本：642
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 9
4. Android 机型：雷电模拟9
5. Android 系统类别：MIUI
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：在638中运行没有问题，在641/642就出现以下问题，原本以为修复打包就开开心心可用了，这就很扎心了。
``` bash
00:49:15.608/V: 开始运行[[remote]main.js]
00:49:15.809/E: Attempt to read from field 'org.mozilla.javascript.Scriptable org.mozilla.javascript.Context.topCallScope' on a null object reference

java.lang.NullPointerException: Attempt to read from field 'org.mozilla.javascript.Scriptable org.mozilla.javascript.Context.topCallScope' on a null object reference
	at org.mozilla.javascript.ScriptRuntime.hasTopCall(ScriptRuntime.java:3831)
	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:87)
	at com.stardust.autojs.core.looper.Timer.callFunction(Timer.kt:43)
	at com.stardust.autojs.core.looper.Timer.setImmediate$lambda-5(Timer.kt:97)
	at com.stardust.autojs.core.looper.Timer.$r8$lambda$6wgwJY18-S6XbhpuNizrQDc4Cr8(Unknown Source:0)
	at com.stardust.autojs.core.looper.Timer$$ExternalSyntheticLambda0.run(Unknown Source:8)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6819)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:860)
00:49:15.810/V: 

```
9. 报错日志（可选）：
10. 屏幕截图（可选）：

**Comment by lanmingle** [comment]
另外测试 641/642 发现：images.requestScreenCapture() 不允许了。

``` ts

const init = (): void => {

    toast('程序准备中...');
    sleep(500);

    toast('检查无障碍权限...');
    sleep(500);
    auto.waitFor();

    toast('检查悬浮窗权限...');
    sleep(500);
    if (!floaty.checkPermission()) {
        floaty.requestPermission();
        exit();
    }

    toast('检查屏幕截图权限...');
    sleep(500);
    if (!images.requestScreenCapture()) {
        toast('请求屏幕截图权限失败');
        exit();
    }

    toast('加载悬浮窗依赖库...');
    sleep(500);
    require('@lanaqi/autox-float-button');

    toast('程序已准备...');
    sleep(500);

};

```

等会一直卡住，不知道为什么！638中没有问题。

**Comment by aiselp** [comment]
最新提交已包含此修复，将会在后续版本修复，对于造成的不便实在抱歉

**Comment by lanmingle** [comment]
好的呢~
