### ISSUE TITLE
使用脚本引擎启动其他脚本文件，在require()导入自定义模块后，使用自带模块会报错的问题

### ISSUE THREAD

**Issue by Zic-0445** [kkevsekk1/AutoX#660]
### bug重现条件：
1. 使用engines.execScriptFile()启动新脚本文件；
2. 新脚本文件中，首行使用require()导入自定义模块；
3. 在require()后，使用storages.create()、images.requestScreenCapture()函数。
___
### 报错内容：
```
TypeError: Cannot read property "autojs" from undefined (/android_asset/modules/__storages__.js#15)
TypeError: Cannot read property "autojs" from undefined
    at LocalStorage (/android_asset/modules/__storages__.js:15:0)
    at /android_asset/modules/__storages__.js:5:0
    at /storage/emulated/0/脚本/test.js:4:0
```
___
### 示例代码：
* main.js
```
engines.execScriptFile("test.js", {
    delay: 3000
})
```
* test.js
```
var com = require("common");

const storage = storages.create("test");

storage.put("test", new Date().getTime());

console.log(storage.get("test"));
```

**Comment by Zic-0445** [comment]
### 临时处理办法：
将```storages.create()```、```images.requestScreenCapture()```置于require()之前，可以正常使用

**Comment by richer0718** [comment]
> com

可以麻烦说的再详细一点吗，全局变量com是哪里
