### ISSUE TITLE
engines.all()会报ConcurrentModificationException

### ISSUE THREAD

**Issue by 1451544363** [kkevsekk1/AutoX#702]
1. Autox.js 版本：629
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 10
4. Android 机型 红米k20
5. Android 系统类别：MIUI
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：
8. 报错日志（可选）：
9. 屏幕截图（可选）：
10. `3:50:59.108/E: Wrapped java.util.ConcurrentModificationException (file:///android_asset/modules/__bridges__.js#49)
Wrapped java.util.ConcurrentModificationException
    at file:///android_asset/modules/__bridges__.js:49:0
    at file:///android_asset/modules/__engines__.js:30:0
    at killTask (main_cloud.js.js:349:0)
    at main_cloud.js.js:362:0
    at file:///android_asset/modules/__bridges__.js:10:0`

**Comment by 1451544363** [comment]
在脚本中通过事件发送到主线程中，主线程engines.all()就会报错

3:50:59.108/E: Wrapped java.util.ConcurrentModificationException (file:///android_asset/modules/__bridges__.js#49)
Wrapped java.util.ConcurrentModificationException
    at file:///android_asset/modules/__bridges__.js:49:0
    at file:///android_asset/modules/__engines__.js:30:0
    at killTask (main_cloud.js.js:349:0)
    at main_cloud.js.js:362:0
    at file:///android_asset/modules/__bridges__.js:10:0
