### ISSUE TITLE
越更新月多bug,请进来看

### ISSUE THREAD

**Issue by diuchouni** [kkevsekk1/AutoX#715]
**连接vscode 在ui点击按钮执行exit() 就崩溃了... 不连接vscode就没事**

1. Autox.js 版本：653
3. Android 版本：Android 7
4. Android 机型：模拟器
7. 问题描述：
8. 报错日志（可选）：
java.lang.InterruptedException
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:84)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at org.autojs.autojs.devplugin.DevPlugin$Connection.log(DevPlugin.kt:330)
	at org.autojs.autojs.devplugin.DevPlugin.log(DevPlugin.kt:91)
	at org.autojs.autojs.autojs.AutoJs$3.println(AutoJs.java:119)
	at com.stardust.autojs.core.console.ConsoleImpl.println(ConsoleImpl.java:137)
	at com.stardust.autojs.runtime.api.AbstractConsole.printf(AbstractConsole.java:26)
	at com.stardust.autojs.runtime.api.AbstractConsole.error(AbstractConsole.java:66)
	at com.stardust.autojs.core.console.ConsoleImpl.error(ConsoleImpl.java:356)
	at com.stardust.autojs.ScriptEngineService$Companion$GLOBAL_LISTENER$1.onException(ScriptEngineService.kt:225)
	at com.stardust.autojs.execution.ScriptExecutionObserver.onException(ScriptExecutionObserver.java:29)
	at com.stardust.autojs.execution.ScriptExecuteActivity.onException(ScriptExecuteActivity.kt:77)
	at com.stardust.autojs.execution.ScriptExecuteActivity.finish(ScriptExecuteActivity.kt:115)
	at com.stardust.autojs.engine.LoopBasedJavaScriptEngine.forceStop(LoopBasedJavaScriptEngine.java:82)
	at com.stardust.autojs.runtime.ScriptRuntime.exit(ScriptRuntime.java:378)
	at com.stardust.autojs.runtime.ScriptRuntime.exit(ScriptRuntime.java:387)
	at com.stardust.autojs.runtime.ScriptBridges$callFunction$1.invoke(ScriptBridges.kt:48)
	at com.stardust.autojs.runtime.ScriptBridges$callFunction$1.invoke(ScriptBridges.kt:36)
	at com.stardust.autojs.runtime.ScriptBridges.useJsContext(ScriptBridges.kt:30)
	at com.stardust.autojs.runtime.ScriptBridges.callFunction(ScriptBridges.kt:36)
	at com.stardust.autojs.core.eventloop.EventEmitter$Listeners.emit(EventEmitter.java:59)
	at com.stardust.autojs.core.eventloop.EventEmitter.emit(EventEmitter.java:140)
	at com.stardust.autojs.execution.ScriptExecuteActivity.emit(ScriptExecuteActivity.kt:194)
	at com.stardust.autojs.execution.ScriptExecuteActivity.onOptionsItemSelected(ScriptExecuteActivity.kt:188)
	at android.app.Activity.onMenuItemSelected(Activity.java:3226)
	at androidx.activity.ComponentActivity.onMenuItemSelected(ComponentActivity.java:514)
	at androidx.fragment.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:352)
	at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:266)
	at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:110)
	at androidx.appcompat.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:66)
	at androidx.appcompat.widget.Toolbar$1.onMenuItemClick(Toolbar.java:221)
	at androidx.appcompat.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:781)
	at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:836)
	at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:159)
	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:987)
	at androidx.appcompat.view.menu.MenuPopup.onItemClick(MenuPopup.java:128)
	at android.widget.AdapterView.performItemClick(AdapterView.java:310)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1164)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3132)
	at android.widget.AbsListView$3.run(AbsListView.java:4047)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6205)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:892)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782)

**还有打包带有图色后的app 少个c++的so.. 这个问题几个版本了.都没修复下的吗? **

**Comment by aiselp** [comment]
已确认问题。
由于调用exit()后当前线程被标记为正在中断，此时DevPlugin.kt:330 中使用了runBlocking则会抛出异常。
解决方法:只需要更换使用非当前线程的协程上下文即可
