### ISSUE TITLE
[Bug][Webview] Can not use webview on android 11

### ISSUE THREAD

**Issue by anhnhoktvn** [kkevsekk1/AutoX#729]
1. Autox.js version: 6.5.3
2. Autox.js download channel: https://github.com/kkevsekk1/AutoX/releases
3. Android version: Android 11
4. Android model:  11
5. Android system category: android 11
6. VSCODE Autox.js extension version (optional, if it is a problem with connecting to a computer, it needs to be filled in):
7. Problem description:
only on android 11
can not use floaty with webview, run this code
```
floaty.window(`
    <vertical>
        <webview id="web" h="*"/>
    </vertical>`)
```

it works normally if remove webview
```
floaty.window(`
    <vertical>
    </vertical>`)

```

updated: it's webview problem, not floaty

also got error without floaty
```
'ui';
ui.layout(`
    <vertical>
        <webview id="web" h="*"/>
    </vertical>`)

```
```
12:15:45.489/V: Start operation[[remote]test.js]
12:15:45.587/E: Wrapped android.view.InflateException: android.view.InflateException: java.lang.reflect.InvocationTargetException (/android_asset/modules/__ui__.js#18)
Wrapped android.view.InflateException: android.view.InflateException: java.lang.reflect.InvocationTargetException
    at /android_asset/modules/__ui__.js:18:0
    at [remote]test.js:2:0

12:15:45.589/V: 
 ------------ 
 [ [remote]test.js ] Finished running in 0.086000 seconds

```
9. Error log (optional):
```
12:02:30.818/V: Start operation[[remote]test.js]
12:02:30.886/E: JavaException: java.lang.NullPointerException: Attempt to invoke virtual method 'com.stardust.autojs.runtime.ScriptRuntime com.stardust.autojs.engine.RhinoJavaScriptEngine.getRuntime()' on a null object reference (/android_asset/modules/__ui__.js#98)
JavaException: java.lang.NullPointerException: Attempt to invoke virtual method 'com.stardust.autojs.runtime.ScriptRuntime com.stardust.autojs.engine.RhinoJavaScriptEngine.getRuntime()' on a null object reference
    at /android_asset/modules/__ui__.js:98:0
    at /android_asset/modules/__floaty__.js:10:0
    at [remote]test.js:1:0

12:02:30.888/V: 
 ------------ 
 [ [remote]test.js ] Finished running in 0.069000 seconds

```

10. Screenshot (optional):

**Comment by anhnhoktvn** [comment]
Update webview from google play store fixed it
