### ISSUE TITLE
是否有方法可以直接访问内置类，例如UiObject

### ISSUE THREAD

**Issue by Pandaver** [kkevsekk1/AutoX#797]
1. Autox.js 版本：656
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 10
4. Android 机型：小米10
5. Android 系统类别：MIUI
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：
8. 报错日志（可选）：
9. 屏幕截图（可选）：

```js
UiObject.prototype.realClick = function (randomDelayMaxMs = 200, randomDelayMinMs = 0) {
  const { left, right, top, bottom } = this.bounds()
  const randomX = random(left, right)
  const randomY = random(top, bottom)
  random(randomDelayMinMs, randomDelayMaxMs)
  click(randomX, randomY)
}
```
打包运行后报错
```log
9:27:41.020/E: ReferenceError: "UiObject" is not defined. ([remote]app.js#97(eval)#3)
ReferenceError: "UiObject" is not defined.
    at [remote]app.js#97(eval):3:0
    at [remote]app.js:97:0
    at __webpack_require__ ([remote]app.js:20:0)
    at [remote]app.js:84:0
    at [remote]app.js:1:0
```

**Comment by aiselp** [comment]
这是一个java类，没有办法修改它的prototype

**Comment by Pandaver** [comment]
之前用ajpro是可以修改的
