### ISSUE TITLE
shell am force-stop 执行失败

### ISSUE THREAD

**Issue by 74566547** [kkevsekk1/AutoX#805]
1. Autox.js 版本：6.5.7
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 13
4. Android 机型：Iqoo 10
5. Android 系统类别：originos3
6. VSCODE Autox.js 扩展版本：v.1.109.0
7. 问题描述：执行shell am force-stop 失败
8. 报错日志（可选）：
   Exception occurred while executing 'force-stop':
   java.lang.SecurityException: Permission Denial: forceStopPackage() from pid=9276, uid=10328 requires android.permission.FORCE_STOP_PACKAGES
	  at com.android.server.am.ActivityManagerService.forceStopPackage(ActivityManagerService.java:4685)
	  at com.android.server.am.ActivityManagerService.forceStopPackage(ActivityManagerService.java:4671)
	  at com.android.server.am.ActivityManagerShellCommand.runForceStop(ActivityManagerShellCommand.java:1283)
	  at com.android.server.am.ActivityManagerShellCommand.onCommand(ActivityManagerShellCommand.java:272)
	  at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)
	  at android.os.ShellCommand.exec(ShellCommand.java:38)
	  at com.android.server.am.ActivityManagerService.onShellCommand(ActivityManagerService.java:10380)
	  at android.os.Binder.shellCommand(Binder.java:1110)
	  at android.os.Binder.onTransact(Binder.java:938)
	  at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:5612)
	  at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3128)
	  at android.os.Binder.execTransactInternal(Binder.java:1346)
	  at android.os.Binder.execTransact(Binder.java:1305)
  ', result=''}
10. 屏幕截图（可选）：
<img width="233" alt="image" src="https://github.com/kkevsekk1/AutoX/assets/153059585/819a0072-2dc8-4294-9fef-229f153450d5">

<img width="921" alt="image" src="https://github.com/kkevsekk1/AutoX/assets/153059585/50bfe09d-958a-4de0-9bca-f92a44102353">

**Comment by 1061700625** [comment]
shell('xxxxxx', true)
加true表示需要root权限

**Comment by 74566547** [comment]
> shell('xxxxxx', true) 加true表示需要root权限

如果没有root权限就不可以了吗？

**Comment by 1061700625** [comment]
我不清楚，你可以用安卓模拟器试试
