### ISSUE TITLE
6.5.9 更新后报错，6.5.8可以正常运行

### ISSUE THREAD

**Issue by gaomanyi** [kkevsekk1/AutoX#876]
1. Autox.js 版本：659
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 14
4. Android 机型：redmi note t 12
5. Android 系统类别：hyper
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：
8. 报错日志（可选）：
9. 屏幕截图（可选）：

java.lang.OutOfMemoryError: Failed to allocate a 96 byte allocation with 12704 free bytes and 12KB until OOM, target footprint 536870912, growth limit 536870912; giving up on allocation because <1% of heap free after GC.
	at android.os.perfdebug.MessageMonitorImpl$MessageMonitorInfoImpl.markDispatch(MessageMonitorImpl.java:999)
	at android.os.perfdebug.MessageMonitorImpl.markDispatch(MessageMonitorImpl.java:287)
	at android.os.Looper.loopOnce(Looper.java:193)
	at android.os.Looper.loop(Looper.java:318)
	at android.app.ActivityThread.main(ActivityThread.java:8759)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)

**Comment by xujun05** [comment]
same error
