### ISSUE TITLE
执行 UiSelector.find() 一定会触发 java.lang.StackOverflowError

### ISSUE THREAD

**Issue by 0xlau** [kkevsekk1/AutoX#878]
1. Autox.js 版本：629
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 9
4. VSCODE Autox.js 扩展版本
5. 问题描述：执行UiSelector.find()，必定会爆栈溢出
6. 报错日志（可选）：
19:49:25.413/E: Thread[main (Spawn-0),5]: stack size 1041KB

java.lang.StackOverflowError: stack size 1041KB
	at org.mozilla.javascript.IdScriptableObject.initPrototypeMethod(IdScriptableObject.java:763)
	at org.mozilla.javascript.NativeMap.initPrototypeId(NativeMap.java:205)
	at org.mozilla.javascript.IdScriptableObject$PrototypeValues.ensureId(IdScriptableObject.java:290)
	at org.mozilla.javascript.IdScriptableObject$PrototypeValues.get(IdScriptableObject.java:162)
	at org.mozilla.javascript.IdScriptableObject.get(IdScriptableObject.java:402)
	at org.mozilla.javascript.NativeMap.init(NativeMap.java:28)
	at org.mozilla.javascript.ScriptRuntime.initSafeStandardObjects(ScriptRuntime.java:283)
	at org.mozilla.javascript.ScriptRuntime.initStandardObjects(ScriptRuntime.java:300)
	at org.mozilla.javascript.Context.initStandardObjects(Context.java:1081)
	at org.mozilla.javascript.Context.initStandardObjects(Context.java:985)
	at com.stardust.autojs.runtime.ScriptBridges$toArray$1.invoke(ScriptBridges.kt:55)
	at com.stardust.autojs.runtime.ScriptBridges$toArray$1.invoke(ScriptBridges.kt:54)
	at com.stardust.autojs.runtime.ScriptBridges.useJsContext(ScriptBridges.kt:30)
	at com.stardust.autojs.runtime.ScriptBridges.toArray(ScriptBridges.kt:54)
	at com.stardust.autojs.runtime.ScriptBridges$asArray$1.invoke(ScriptBridges.kt:66)
	at com.stardust.autojs.runtime.ScriptBridges$asArray$1.invoke(ScriptBridges.kt:65)
	at com.stardust.autojs.runtime.ScriptBridges.useJsContext(ScriptBridges.kt:30)
	at com.stardust.autojs.runtime.ScriptBridges.asArray(ScriptBridges.kt:65)
	at com.stardust.autojs.rhino.AndroidContextFactory$WrapFactory.wrap(AndroidContextFactory.kt:79)
	at org.mozilla.javascript.Context.javaToJS(Context.java:1725)
	at org.mozilla.javascript.Context.javaToJS(Context.java:1684)
	at com.stardust.autojs.runtime.ScriptBridges$asArray$1.invoke(ScriptBridges.kt:67)
	at com.stardust.autojs.runtime.ScriptBridges$asArray$1.invoke(ScriptBridges.kt:65)
	at com.stardust.autojs.runtime.ScriptBridges.useJsContext(ScriptBridges.kt:30)
	at com.stardust.autojs.runtime.ScriptBridges.asArray(ScriptBridges.kt:65)
	at com.stardust.autojs.rhino.AndroidContextFactory$WrapFactory.wrap(AndroidContextFactory.kt:79)
	at org.mozilla.javascript.Context.javaToJS(Context.java:1725)
	at org.mozilla.javascript.Context.javaToJS(Context.java:1684)
	at com.stardust.autojs.runtime.ScriptBridges$asArray$1.invoke(ScriptBridges.kt:67)
	at com.stardust.autojs.runtime.ScriptBridges$asArray$1.invoke(ScriptBridges.kt:65)
	at com.stardust.autojs.runtime.ScriptBridges.useJsContext(ScriptBridges.kt:30)
	at com.stardust.autojs.runtime.ScriptBridges.asArray(ScriptBridges.kt:65)
	at com.stardust.autojs.rhino.AndroidContextFactory$WrapFactory.wrap(AndroidContextFactory.kt:79)
	at org.mozilla.javascript.Context.javaToJS(Context.java:1725)
	at org.mozilla.javascript.Context.javaToJS(Context.java:1684)
	at com.stardust.autojs.runtime.ScriptBridges$asArray$1.invoke(ScriptBridges.kt:67)
	at com.stardust.autojs.runtime.ScriptBridges$asArray$1.invoke(ScriptBridges.kt:65)
	at com.stardust.autojs.runtime.ScriptBridges.useJsContext(ScriptBridges.kt:30)
	at com.stardust.autojs.runtime.ScriptBridges.asArray(ScriptBridges.kt:65)
	at com.stardust.autojs.rhino.AndroidContextFactory$WrapFactory.wrap(AndroidContextFactory.kt:79)
。。。。。。
。。。。。
。。。
。。
。
	at org.mozilla.javascript.Context.javaToJS(Context.java:1725)
	at org.mozilla.javascript.Context.javaToJS(Context.java:1684)
	at com.stardust.autojs.runtime.ScriptBridges$asArray$1.invoke(ScriptBridges.kt:67)
	at com.stardust.autojs.runtime.ScriptBridges$asArray$1.invoke(ScriptBridges.kt:65)
	at com.stardust.autojs.runtime.ScriptBridges.useJsContext(ScriptBridges.kt:30)
	at com.stardust.autojs.runtime.ScriptBridges.asArray(ScriptBridges.kt:65)
	at com.stardust.autojs.rhino.AndroidContextFactory$WrapFactory.wrap(AndroidContextFactory.kt:79)
	at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:227)
	at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1879)
	at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:1061)
	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:90)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:380)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3869)
	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:88)
	at org.mozilla.javascript.InterfaceAdapter.invokeImpl(InterfaceAdapter.java:171)
	at org.mozilla.javascript.VMBridge_custom$InterfaceAdapterWrapper.invokeImpl(VMBridge_custom.java:151)
	at org.mozilla.javascript.VMBridge_custom$InterfaceAdapterWrapper.lambda$invoke$0(VMBridge_custom.java:133)
	at org.mozilla.javascript.VMBridge_custom$InterfaceAdapterWrapper.$r8$lambda$GM2BaIWLqJsbHoNPr8Zc4jy_3KI(Unknown Source:0)
	at org.mozilla.javascript.VMBridge_custom$InterfaceAdapterWrapper$$ExternalSyntheticLambda0.run(Unknown Source:13)
	at org.mozilla.javascript.VMBridge_custom$InterfaceAdapterWrapper.call(VMBridge_custom.java:142)
	at org.mozilla.javascript.VMBridge_custom$InterfaceAdapterWrapper.invoke(VMBridge_custom.java:134)
	at org.mozilla.javascript.VMBridge_custom.lambda$newInterfaceProxy$0(VMBridge_custom.java:67)
	at org.mozilla.javascript.VMBridge_custom.$r8$lambda$ML7_55cjdL8MKr7ULnzHaRFuHdU(Unknown Source:0)
	at org.mozilla.javascript.VMBridge_custom$$ExternalSyntheticLambda0.invoke(Unknown Source:15)
	at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
	at $Proxy6.run(Unknown Source)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at com.stardust.autojs.core.looper.TimerThread.run(TimerThread.kt:33) 
7. 屏幕截图（可选）：
<img width="924" alt="image" src="https://github.com/kkevsekk1/AutoX/assets/45397727/f8194ab3-a9ce-402c-a884-6ce36da1b3af">

**Comment by cykaifen** [comment]
我也遇到同样的问题了。请大神指教。

**Comment by imeepos** [comment]
find()查出来的结果太多了，内存存不下，溢出了

**Comment by imeepos** [comment]
优化下你的代码

**Comment by cykaifen** [comment]
不是代码的问题。模拟器给了4G的内存。以前在autojs里是可以正常运行的。
最近换成autox.js后，很容易就出现内存溢出的问题。
这个堆栈空间自已能设置成更大的空间吗？ 像eclipse里是可以设置内存空间。

java.lang.StackOverflowError: stack size 1041KB
at org.mozilla.javascript.IdScriptableObject.initPrototypeMethod(IdScriptableObject.java:763)
at org.mozilla.javascript.NativeMap.initPrototypeId(NativeMap.java:205)
at org.mozilla.javascript.IdScriptableObject$PrototypeValues.ensureId(IdScriptableObject.java:290)
at org.mozilla.javascript.IdScriptableObject$PrototypeValues.get(IdScriptableObject.java:162)
at org.mozilla.javascript.IdScriptableObject.get(IdScriptableObject.java:402)
at org.mozilla.javascript.NativeMap.init(NativeMap.java:28)
at org.mozilla.javascript.ScriptRuntime.initSafeStandardObjects(ScriptRuntime.java:283)
at org.mozilla.javascript.ScriptRuntime.initStandardObjects(ScriptRuntime.java:300)
at org.mozilla.javascript.Context.initStandardObjects(Context.java:1081)
at org.mozilla.javascript.Context.initStandardObjects(Context.java:985)
at com.stardust.autojs.runtime.ScriptBridges$toArray$1.invoke(ScriptBridges.kt:55)
at com.stardust.autojs.runtime.ScriptBridges$toArray$1.invoke(ScriptBridges.kt:54)
at com.stardust.autojs.runtime.ScriptBridges.useJsContext(ScriptBridges.kt:30)
at com.stardust.autojs.runtime.ScriptBridges.toArray(ScriptBridges.kt:54)
at com.stardust.autojs.runtime.ScriptBridges$asArray$1.invoke(ScriptBridges.kt:66)
at com.stardust.autojs.runtime.ScriptBridges$asArray$1.invoke(ScriptBridges.kt:65)
at com.stardust.autojs.runtime.ScriptBridges.useJsContext(ScriptBridges.kt:30)
at com.stardust.autojs.runtime.ScriptBridges.asArray(ScriptBridges.kt:65)
at com.stardust.autojs.rhino.AndroidContextFactory$WrapFactory.wrap(AndroidContextFactory.kt:79)
at org.mozilla.javascript.Context.javaToJS(Context.java:1725)
at org.mozilla.javascript.Context.javaToJS(Context.java:1684)
at com.stardust.autojs.runtime.ScriptBridges$asArray$1.invoke(ScriptBridges.kt:67)
at com.stardust.autojs.runtime.ScriptBridges$asArray$1.invoke(ScriptBridges.kt:65)
at com.stardust.autojs.runtime.ScriptBridges.useJsContext(ScriptBridges.kt:30)
at com.stardust.autojs.runtime.ScriptBridges.asArray(ScriptBridges.kt:65)
at com.stardust.autojs.rhino.AndroidContextFactory$WrapFactory.wrap(AndroidContextFactory.kt:79)
at org.mozilla.javascript.Context.javaToJS(Context.java:1725)
at org.mozilla.javascript.Context.javaToJS(Context.java:1684)
at com.stardust.autojs.runtime.ScriptBridges$asArray$1.invoke(ScriptBridges.kt:67)
at com.stardust.autojs.runtime.ScriptBridges$asArray$1.invoke(ScriptBridges.kt:65)
at com.stardust.autojs.runtime.ScriptBridges.useJsContext(ScriptBridges.kt:30)
at com.stardust.autojs.runtime.ScriptBridges.asArray(ScriptBridges.kt:65)
at com.stardust.autojs.rhino.AndroidContextFactory$WrapFactory.wrap(AndroidContextFactory.kt:79)
at org.mozilla.javascript.Context.javaToJS(Context.java:1725)
at org.mozilla.javascript.Context.javaToJS(Context.java:1684)
at com.stardust.autojs.runtime.ScriptBridges$asArray$1.invoke(ScriptBridges.kt:67)
at com.stardust.autojs.runtime.ScriptBridges$asArray$1.invoke(ScriptBridges.kt:65)
at com.stardust.autojs.runtime.ScriptBridges.useJsContext(ScriptBridges.kt:30)
at com.stardust.autojs.runtime.ScriptBridges.asArray(ScriptBridges.kt:65)
at com.stardust.autojs.rhino.AndroidContextFactory$WrapFactory.wrap(AndroidContextFactory.kt:79)
