### ISSUE TITLE
OutOfMemoryError

### ISSUE THREAD

**Issue by halejohn** [kkevsekk1/AutoX#888]
1. Autox.js 版本：6.5.8
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 9
4. Android 机型：pixel3 
5. Android 系统类别：aosp
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：无
7. 问题描述：
8. 报错日志：
java.lang.OutOfMemoryError: Failed to allocate a 524304 byte allocation with 263880 free bytes and 257KB until OOM, max allowed footprint 536870912, growth limit 536870912
	at org.mozilla.javascript.Decompiler.increaseSourceCapacity(Decompiler.java:207)
	at org.mozilla.javascript.Decompiler.appendString(Decompiler.java:178)
	at org.mozilla.javascript.Decompiler.addString(Decompiler.java:102)
	at org.mozilla.javascript.IRFactory.transformString(IRFactory.java:1144)
	at org.mozilla.javascript.IRFactory.transform(IRFactory.java:203)
	at org.mozilla.javascript.IRFactory.transformInfix(IRFactory.java:857)
	at org.mozilla.javascript.IRFactory.transform(IRFactory.java:234)
	at org.mozilla.javascript.IRFactory.transformInfix(IRFactory.java:855)
	at org.mozilla.javascript.IRFactory.transform(IRFactory.java:234)
	at org.mozilla.javascript.IRFactory.transformInfix(IRFactory.java:857)
	at org.mozilla.javascript.IRFactory.transform(IRFactory.java:234)
	at org.mozilla.javascript.IRFactory.transformParenExpr(IRFactory.java:1039)
	at org.mozilla.javascript.IRFactory.transform(IRFactory.java:240)
	at org.mozilla.javascript.IRFactory.transformReturn(IRFactory.java:1120)
	at org.mozilla.javascript.IRFactory.transform(IRFactory.java:199)
	at org.mozilla.javascript.IRFactory.transformBlock(IRFactory.java:488)
	at org.mozilla.javascript.IRFactory.transform(IRFactory.java:147)
	at org.mozilla.javascript.IRFactory.transformFunction(IRFactory.java:633)
	at org.mozilla.javascript.IRFactory.transform(IRFactory.java:165)
	at org.mozilla.javascript.IRFactory.transformAssignment(IRFactory.java:448)
	at org.mozilla.javascript.IRFactory.transform(IRFactory.java:222)
	at org.mozilla.javascript.IRFactory.transformExprStmt(IRFactory.java:559)
	at org.mozilla.javascript.IRFactory.transform(IRFactory.java:219)
	at org.mozilla.javascript.IRFactory.transformBlock(IRFactory.java:488)
	at org.mozilla.javascript.IRFactory.transform(IRFactory.java:147)
	at org.mozilla.javascript.IRFactory.transformFunction(IRFactory.java:633)
	at org.mozilla.javascript.IRFactory.transform(IRFactory.java:165)
	at org.mozilla.javascript.IRFactory.transformAssignment(IRFactory.java:448)
	at org.mozilla.javascript.IRFactory.transform(IRFactory.java:222)
	at org.mozilla.javascript.IRFactory.transformExprStmt(IRFactory.java:559)
	at org.mozilla.javascript.IRFactory.transform(IRFactory.java:219)
	at org.mozilla.javascript.IRFactory.transformBlock(IRFactory.java:488)
	at org.mozilla.javascript.IRFactory.transform(IRFactory.java:147)
	at org.mozilla.javascript.IRFactory.transformFunction(IRFactory.java:633)
	at org.mozilla.javascript.IRFactory.transform(IRFactory.java:165)
	at org.mozilla.javascript.IRFactory.transformParenExpr(IRFactory.java:1039)
	at org.mozilla.javascript.IRFactory.transform(IRFactory.java:240)
	at org.mozilla.javascript.IRFactory.transformObjectLiteral(IRFactory.java:990)
	at org.mozilla.javascript.IRFactory.transform(IRFactory.java:191)
	at org.mozilla.javascript.IRFactory.transformParenExpr(IRFactory.java:1039)
	at org.mozilla.javascript.IRFactory.transform(IRFactory.java:240)
	at org.mozilla.javascript.IRFactory.transformVariableInitializers(IRFactory.java:1325)
	at org.mozilla.javascript.IRFactory.transformVariables(IRFactory.java:1296)
	at org.mozilla.javascript.IRFactory.transform(IRFactory.java:237)
	at org.mozilla.javascript.IRFactory.transformBlock(IRFactory.java:488)
	at org.mozilla.javascript.IRFactory.transform(IRFactory.java:147)
	at org.mozilla.javascript.IRFactory.transformFunction(IRFactory.java:633)
	at org.mozilla.javascript.IRFactory.transform(IRFactory.java:165)
	at org.mozilla.javascript.IRFactory.transformParenExpr(IRFactory.java:1039)
	at org.mozilla.javascript.IRFactory.transform(IRFactory.java:240)
	at org.mozilla.javascript.IRFactory.transformFunctionCall(IRFactory.java:667)
	at org.mozilla.javascript.IRFactory.transform(IRFactory.java:151)
	at org.mozilla.javascript.IRFactory.transformExprStmt(IRFactory.java:559)
	at org.mozilla.javascript.IRFactory.transform(IRFactory.java:219)
	at org.mozilla.javascript.IRFactory.transformScript(IRFactory.java:1133)
	at org.mozilla.javascript.IRFactory.transform(IRFactory.java:201)
	at org.mozilla.javascript.IRFactory.transformTree(IRFactory.java:121)
	at org.mozilla.javascript.Context.parse(Context.java:2489)
	at org.mozilla.javascript.Context.compileImpl(Context.java:2406)
	at org.mozilla.javascript.Context.compileReader(Context.java:1330)
	at org.mozilla.javascript.commonjs.module.provider.CachingModuleScriptProviderBase.getModuleScript(CachingModuleScriptProviderBase.java:86)
	at org.mozilla.javascript.commonjs.module.provider.SoftCachingModuleScriptProvider.getModuleScript(SoftCachingModuleScriptProvider.java:61)
	at com.stardust.autojs.engine.module.ScopeRequire.getModule(ScopeRequire.kt:188)
	at com.stardust.autojs.engine.module.ScopeRequire.loadModule(ScopeRequire.kt:54)
	at com.stardust.autojs.engine.module.ScopeRequire.call(ScopeRequire.kt:104)
	at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1879)
	at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:1061)
	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:90)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:380)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3869)
	at org.mozilla.javascript.Context.callFunctionWithContinuations(Context.java:1225)
	at org.mozilla.javascript.Context.executeScriptWithContinuations(Context.java:1193)
	at com.stardust.autojs.engine.RhinoJavaScriptEngine.init(RhinoJavaScriptEngine.kt:104)
	at com.stardust.autojs.engine.LoopBasedJavaScriptEngine.init(LoopBasedJavaScriptEngine.java:91)
	at com.stardust.autojs.execution.RunnableScriptExecution.prepare(RunnableScriptExecution.java:68)
	at com.stardust.autojs.execution.RunnableScriptExecution.execute(RunnableScriptExecution.java:42)
	at com.stardust.autojs.execution.RunnableScriptExecution.execute(RunnableScriptExecution.java:37)
	at com.stardust.autojs.execution.RunnableScriptExecution.run(RunnableScriptExecution.java:31)
	at java.lang.Thread.run(Thread.java:764)
06:38:58.535/E: Failed to allocate a 524304 byte allocation with 275304 free bytes and 252KB until OOM, max allowed footprint 536870912, growth limit 536870912

**Comment by imeepos** [comment]
正常报错，程序优化一下
