### ISSUE TITLE
异常退出

### ISSUE THREAD

**Issue by fanlushuai** [kkevsekk1/AutoX#902]
1. Autox.js 版本：6.60
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 14
4. Android 机型：oppok10
5. Android 系统类别：coloros
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：
   运行一段时间之后，就会报下面的错误
9. 报错日志（可选）：
Thread[ScriptThread-3[/storage/emulated/0/autojs/mtz/scriptTask.js] (Spawn-0),5]: Parameter specified as non-null is null: method com.stardust.autojs.rhino.AndroidContextFactory$WrapFactory.wrap, parameter scope

java.lang.NullPointerException: Parameter specified as non-null is null: method com.stardust.autojs.rhino.AndroidContextFactory$WrapFactory.wrap, parameter scope
	at com.stardust.autojs.rhino.AndroidContextFactory$WrapFactory.wrap(Unknown Source:7)
	at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:227)
	at org.mozilla.javascript.ScriptableObject.getDefaultValue(ScriptableObject.java:791)
	at org.mozilla.javascript.ScriptableObject.getDefaultValue(ScriptableObject.java:766)
	at org.mozilla.javascript.ScriptRuntime.toPrimitive(ScriptRuntime.java:3326)
	at org.mozilla.javascript.ScriptRuntime.toPrimitive(ScriptRuntime.java:3318)
	at org.mozilla.javascript.ScriptRuntime.eqNumber(ScriptRuntime.java:3512)
	at org.mozilla.javascript.ScriptRuntime.eq(ScriptRuntime.java:3415)
	at org.mozilla.javascript.Interpreter.doEquals(Interpreter.java:3067)
	at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1332)
	at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:1061)
	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:90)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:380)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3869)
	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:88)
	at org.mozilla.javascript.ArrowFunction.call(ArrowFunction.java:43)
	at org.mozilla.javascript.InterfaceAdapter.invokeImpl(InterfaceAdapter.java:171)
	at org.mozilla.javascript.VMBridge_custom$InterfaceAdapterWrapper.invokeImpl(VMBridge_custom.java:151)
	at org.mozilla.javascript.VMBridge_custom$InterfaceAdapterWrapper.lambda$invoke$0(VMBridge_custom.java:133)
	at org.mozilla.javascript.VMBridge_custom$InterfaceAdapterWrapper.$r8$lambda$GM2BaIWLqJsbHoNPr8Zc4jy_3KI(Unknown Source:0)
	at org.mozilla.javascript.VMBridge_custom$InterfaceAdapterWrapper$$ExternalSyntheticLambda0.run(Unknown Source:13)
	at org.mozilla.javascript.VMBridge_custom$InterfaceAdapterWrapper.call(VMBridge_custom.java:142)
	at org.mozilla.javascript.VMBridge_custom$InterfaceAdapterWrapper.invoke(VMBridge_custom.java:134)
	at org.mozilla.javascript.VMBridge_custom.lambda$newInterfaceProxy$0(VMBridge_custom.java:67)
	at org.mozilla.javascript.VMBridge_custom.$r8$lambda$ML7_55cjdL8MKr7ULnzHaRFuHdU(Unknown Source:0)
	at org.mozilla.javascript.VMBridge_custom$$ExternalSyntheticLambda0.invoke(Unknown Source:15)
	at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
	at $Proxy15.run(Unknown Source)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:257)
	at android.os.Looper.loop(Looper.java:368)
	at com.stardust.autojs.core.looper.TimerThread.run(TimerThread.kt:33) 
10. 屏幕截图（可选）：

**Comment by fanlushuai** [comment]
![image](https://github.com/kkevsekk1/AutoX/assets/21078607/b78ef5f1-9b9e-4c9f-941a-72113a2c5ccd)

返回 {}？？？

和以前的返回值应该是不一样了

**Comment by fanlushuai** [comment]
拿findOne结果对象，使用==和普通类型对比，就出现那个错误。


let t=text("目标文本“).findOne()

log(t)
log(t==false)  //如果上面，t找到，log结果为，{} ，这行就会报错。不能直接对比。以前是可以的。

**Comment by aiselp** [comment]
确实有这个问题，打印{}并不影响可使用的函数

**Comment by NOWorEVER** [comment]
设备信息: 
App version: 6.6.0
App version code: 660
Android build version: V816.0.24.2.20.DEV
Android release version: 14
Android SDK version: 34
Android build ID: UKQ1.231003.002 release-keys
Device brand: Xiaomi
Device manufacturer: Xiaomi
Device name: thor
Device model: 2203121C
Device product name: thor
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]

错误信息:
java.util.ConcurrentModificationException: 
java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:760)
java.util.LinkedHashMap$LinkedValueIterator.next(LinkedHashMap.java:787)
org.autojs.autojs.ui.main.task.TaskGroup$RunningTaskGroup.refresh(TaskGroup.java:122)
org.autojs.autojs.ui.main.task.TaskListRecyclerView.refresh(TaskListRecyclerView.java:119)
org.autojs.autojs.ui.main.task.TaskListRecyclerView$1.lambda$onFinish$1(TaskListRecyclerView.java:80)
org.autojs.autojs.ui.main.task.TaskListRecyclerView$1.$r8$lambda$0B-Uylw5MgpZYiuBpM-zsQ6v9VI(Unknown Source:0)
org.autojs.autojs.ui.main.task.TaskListRecyclerView$1$$ExternalSyntheticLambda1.run(Unknown Source:4)
android.os.Handler.handleCallback(Unknown Source:2)
android.os.Handler.dispatchMessage(Unknown Source:4)
android.os.Looper.loopOnce(Unknown Source:198)
android.os.Looper.loop(Unknown Source:83)
android.app.ActivityThread.main(Unknown Source:123)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
com.android.internal.os.ZygoteInit.main(Unknown Source:374)
