### ISSUE TITLE
tasker无法调用脚本(6.6.0), 执行脚本会导致OOM(6.5.9)

### ISSUE THREAD

**Issue by you9you** [kkevsekk1/AutoX#910]
1. Autox.js 版本：6.5.9&6.6.0
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 14
4. Android 机型：小米 MIX 4
5. Android 系统类别：hyperos
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述：
- 6.6.0：tasker无法执行脚本，即autoxjs里没有任何触发日志
- 6.5.9：执行脚本会导致OOM
> 经测试6.5.8可以正常执行
8. 报错日志（可选）：
- 6.6.0：无日志
- 6.5.9：
```
11:16:50.197/E: stack size 1039KB

java.lang.StackOverflowError: stack size 1039KB
	at java.lang.Class.newInstance(Native Method)
	at org.mozilla.javascript.Kit.newInstanceOrNull(Kit.java:46)
	at org.mozilla.javascript.Context.createInterpreter(Context.java:2517)
	at org.mozilla.javascript.RhinoException.<init>(RhinoException.java:29)
	at org.mozilla.javascript.EvaluatorException.<init>(EvaluatorException.java:19)
	at org.mozilla.javascript.NativeError.fillConstructorProperties(NativeError.java:76)
	at org.mozilla.javascript.IdScriptableObject.exportAsJSClass(IdScriptableObject.java:725)
	at org.mozilla.javascript.NativeError.init(NativeError.java:40)
	at org.mozilla.javascript.ScriptRuntime.initSafeStandardObjects(ScriptRuntime.java:162)
	at org.mozilla.javascript.ScriptRuntime.initStandardObjects(ScriptRuntime.java:300)
	at org.mozilla.javascript.Context.initStandardObjects(Context.java:1081)
	at org.mozilla.javascript.Context.initStandardObjects(Context.java:985)
	at com.stardust.autojs.runtime.ScriptBridges$toArray$1.invoke(ScriptBridges.kt:55)
	at com.stardust.autojs.runtime.ScriptBridges$toArray$1.invoke(ScriptBridges.kt:54)
	at com.stardust.autojs.runtime.ScriptBridges.useJsContext(ScriptBridges.kt:30)
	at com.stardust.autojs.runtime.ScriptBridges.toArray(ScriptBridges.kt:54)
	at com.stardust.autojs.runtime.ScriptBridges$asArray$1.invoke(ScriptBridges.kt:66)
	at com.stardust.autojs.runtime.ScriptBridges$asArray$1.invoke(ScriptBridges.kt:65)
	at com.stardust.autojs.runtime.ScriptBridges.useJsContext(ScriptBridges.kt:30)
	at com.stardust.autojs.runtime.ScriptBridges.asArray(ScriptBridges.kt:65)
	at com.stardust.autojs.rhino.AndroidContextFactory$WrapFactory.wrap(AndroidContextFactory.kt:79)
	at org.mozilla.javascript.Context.javaToJS(Context.java:1725)
	at org.mozilla.javascript.Context.javaToJS(Context.java:1684)
	at com.stardust.autojs.runtime.ScriptBridges$asArray$1.invoke(ScriptBridges.kt:67)
	at com.stardust.autojs.runtime.ScriptBridges$asArray$1.invoke(Sc ......<355925>
```

```
11:19:01.122/E: Failed to allocate a 23568 byte allocation with 7360 free bytes and 7360B until OOM, target footprint 536870912, growth limit 536870912

java.lang.OutOfMemoryError: Failed to allocate a 23568 byte allocation with 7360 free bytes and 7360B until OOM, target footprint 536870912, growth limit 536870912
	at org.mozilla.javascript.NativeError.execIdCall(NativeError.java:164)
	at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:100)
	at org.mozilla.javascript.BaseFunction.construct(BaseFunction.java:393)
	at org.mozilla.javascript.ScriptRuntime.newBuiltinObject(ScriptRuntime.java:1302)
	at org.mozilla.javascript.NativeGlobal.init(NativeGlobal.java:112)
	at org.mozilla.javascript.ScriptRuntime.initSafeStandardObjects(ScriptRuntime.java:163)
	at org.mozilla.javascript.ScriptRuntime.initStandardObjects(ScriptRuntime.java:300)
	at org.mozilla.javascript.Context.initStandardObjects(Context.java:1081)
	at org.mozilla.javascript.Context.initStandardObjects(Context.java:985)
	at com.stardust.autojs.runtime.ScriptBridges$toArray$1.invoke(ScriptBridges.kt:55)
	at com.stardust.autojs.runtime.ScriptBridges$toArray$1.invoke(ScriptBridges.kt:54)
	at com.stardust.autojs.runtime.ScriptBridges.useJsContext(ScriptBridges.kt:30)
	at com.stardust.autojs.runtime.ScriptBridges.toArray(ScriptBridges.kt:54)
	at com.stardust.autojs.runtime.ScriptBridges$asArray$1.invoke(ScriptBridges.kt:66)
	at com.stardust.autojs.runtime.ScriptBridges$asArray$1.invoke(ScriptBridges.kt:65)
	at com.stardust.autojs.runtime.ScriptBridges.useJsContext(ScriptBridges.kt:30)
	at com.stardust.autojs.runtime.ScriptBridges.asArray(ScriptBridges.kt:65)
	at com.stardust.autojs.rhino.AndroidContextFactory$WrapFactory.wrap(AndroidContextFactory.kt:79)
	at org.mozilla.javascript.Context.javaToJS(Context.java:1725)
	at org.mozilla.javascript.Context.javaToJS(Context.java:1684)
	at com.stardust.autojs.runtime.ScriptBridges$asArray$1.invoke(ScriptBridges.kt:67)
	at com.stardust.autojs.runtime.Scri ......<455508>
```
9. 屏幕截图（可选）：

**Comment by you9you** [comment]
6.5.9的日志为两次的结果(相同的脚本)
