### ISSUE TITLE
无法启动

### ISSUE THREAD

**Issue by vmaskday** [kkevsekk1/AutoX#947]
1. Autox.js 版本：661
2. Autox.js 下载渠道：https://github.com/kkevsekk1/AutoX/releases
3. Android 版本：Android 14
4. Android 机型 : 魅族20 无界版
5. Android 系统类别：Flyme 10.5.5
6. VSCODE Autox.js 扩展版本（可选，如果是连接电脑的问题需要填）：
7. 问题描述： 无法启动。
8. 报错日志（可选）：logcat
9. 屏幕截图（可选）：

05-23 10:11:28.075  2869  2947 I ActivityManager: Start proc 19171:org.autojs.autoxjs.v6/u0a236 for top-activity {org.autojs.autoxjs.v6/org.autojs.autojs.ui.error.ErrorReportActivity}
05-23 10:11:28.077 19171 19171 W Zygote  : mz_is_rooted false
05-23 10:11:28.079 19171 19171 W libc    : Access denied finding property "persist.vendor.meizu.smart_zram"
05-23 10:11:28.074 19171 19171 W main    : type=1400 audit(0.0:220428): avc:  denied  { read } for  name="u:object_r:vendor_default_prop:s0" dev="tmpfs" ino=412 scontext=u:r:zygote:s0 tcontext=u:object_r:vendor_default_prop:s0 tclass=file permissive=0
05-23 10:11:28.082 19171 19171 E tojs.autoxjs.v6: Unknown bits set in runtime_flags: 0x2000000
05-23 10:11:28.082 19171 19171 I tojs.autoxjs.v6: Using CollectorTypeCC GC.
05-23 10:11:28.084 19171 19171 E tojs.autoxjs.v6: Not starting debugger since process cannot load the jdwp agent.
05-23 10:11:28.089  1636  6570 E ANDR-PERF-LM: MetaMeter: handleAsync() 166: AdaptLaunch Invalid Async
05-23 10:11:28.090  2869  3870 I ActivityTaskManager: Process org.autojs.autoxjs.v6 restarted
05-23 10:11:28.094 20294 20318 I TriggerManager: notifyEvent:EVENT_ACTIVITY, obj=ActivityEvent{activity=org.autojs.autojs.ui.error.ErrorReportActivity, urlType=NONE, url=}
05-23 10:11:28.094  1511  6329 I vendor.qti.bluetooth@1.1-ibs_handler: ProcessIbsCmd: Received IBS_SLEEP_IND: 0xFE
05-23 10:11:28.095  1726  2078 E CompositionEngine: setupHBM: no HWC layer found (RegionSampling for 131)
05-23 10:11:28.095 19171 19181 I tojs.autoxjs.v6: background compaction ignored due to jank perceptible process state
05-23 10:11:28.101 19171 19171 I Perf    : Connecting to perf service.
05-23 10:11:28.105 19171 19171 I MultiDex: VM with version 2.1.0 has multidex support
05-23 10:11:28.105 19171 19171 I MultiDex: Installing application
05-23 10:11:28.105 19171 19171 I MultiDex: VM has multidex support, MultiDex support library is disabled.
05-23 10:11:28.105 19171 19171 W libc    : Access denied finding property "qemu.sf.lcd_density"
05-23 10:11:28.106 19171 19171 W libc    : Access denied finding property "qemu.sf.lcd_density"
05-23 10:11:28.102 19171 19171 W tojs.autoxjs.v6: type=1400 audit(0.0:220429): avc:  denied  { read } for  name="u:object_r:qemu_sf_lcd_density_prop:s0" dev="tmpfs" ino=313 scontext=u:r:untrusted_app:s0:c236,c256,c512,c768 tcontext=u:object_r:qemu_sf_lcd_density_prop:s0 tclass=file permissive=0
05-23 10:11:28.102 19171 19171 W tojs.autoxjs.v6: type=1400 audit(0.0:220430): avc:  denied  { read } for  name="u:object_r:qemu_sf_lcd_density_prop:s0" dev="tmpfs" ino=313 scontext=u:r:untrusted_app:s0:c236,c256,c512,c768 tcontext=u:object_r:qemu_sf_lcd_density_prop:s0 tclass=file permissive=0
05-23 10:11:28.115  1511  6329 I vendor.qti.bluetooth@1.1-ibs_handler: ProcessIbsCmd: Received IBS_WAKE_IND: 0xFD
05-23 10:11:28.115  1511  6329 I vendor.qti.bluetooth@1.1-ibs_handler: ProcessIbsCmd: Writing IBS_WAKE_ACK
05-23 10:11:28.123   993   993 E KeymasterUtils: rsp_header->status: -28
05-23 10:11:28.123   993   993 E KeyMasterHalDevice: abort_operation
05-23 10:11:28.123   993   993 E KeyMasterHalDevice: ret: -28
05-23 10:11:28.133   993   993 E KeymasterUtils: rsp_header->status: -28
05-23 10:11:28.133   993   993 E KeyMasterHalDevice: abort_operation
05-23 10:11:28.133   993   993 E KeyMasterHalDevice: ret: -28
05-23 10:11:28.133 19171 19195 W FlurryAgent: There is a problem with the Google Play Services library, which is required for Android Advertising ID support. The Google Play Services library is recommended to be integrated in any app shipping in the Play Store that uses analytics or advertising.
05-23 10:11:28.143   993   993 E KeymasterUtils: rsp_header->status: -28
05-23 10:11:28.143   993   993 E KeyMasterHalDevice: abort_operation
05-23 10:11:28.143   993   993 E KeyMasterHalDevice: ret: -28
05-23 10:11:28.147 19171 19195 W FlurryAgent: There is a problem with the Google Play Services library, which is required for Android Advertising ID support. The Google Play Services library is recommended to be integrated in any app shipping in the Play Store that uses analytics or advertising.
05-23 10:11:28.148 19171 19195 W FlurryAgent: There is a problem with the Google Play Services library, which is required for Android Advertising ID support. The Google Play Services library is recommended to be integrated in any app shipping in the Play Store that uses analytics or advertising.
05-23 10:11:28.149 19171 19195 W FlurryAgent: There is a problem with the Google Play Services library, which is required for Android Advertising ID support. The Google Play Services library is recommended to be integrated in any app shipping in the Play Store that uses analytics or advertising.
05-23 10:11:28.155  1511  6329 I vendor.qti.bluetooth@1.1-ibs_handler: ProcessIbsCmd: Received IBS_SLEEP_IND: 0xFE
05-23 10:11:28.167 19171 19171 I GlobalAppContext: BuildConfig(DEBUG=false, APPLICATION_ID=org.autojs.autoxjs.v6, BUILD_TYPE=release, FLAVOR=v6, VERSION_CODE=634, VERSION_NAME=6.3.4)
05-23 10:11:28.172 19171 19171 I CrashReport-Native: register native abi method success
05-23 10:11:28.187 19171 19171 E AndroidRuntime: FATAL EXCEPTION: main
05-23 10:11:28.187 19171 19171 E AndroidRuntime: Process: org.autojs.autoxjs.v6, PID: 19171
05-23 10:11:28.187 19171 19171 E AndroidRuntime: java.lang.RuntimeException: Unable to create application org.autojs.autojs.App: java.lang.SecurityException: org.autojs.autoxjs.v6: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
05-23 10:11:28.187 19171 19171 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7153)
05-23 10:11:28.187 19171 19171 E AndroidRuntime: 	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
05-23 10:11:28.187 19171 19171 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2278)
05-23 10:11:28.187 19171 19171 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
05-23 10:11:28.187 19171 19171 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:205)
05-23 10:11:28.187 19171 19171 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:294)
05-23 10:11:28.187 19171 19171 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8358)
05-23 10:11:28.187 19171 19171 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-23 10:11:28.187 19171 19171 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
05-23 10:11:28.187 19171 19171 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:977)
05-23 10:11:28.187 19171 19171 E AndroidRuntime: Caused by: java.lang.SecurityException: org.autojs.autoxjs.v6: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
05-23 10:11:28.187 19171 19171 E AndroidRuntime: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
05-23 10:11:28.187 19171 19171 E AndroidRuntime: 	at android.os.Parcel.createException(Parcel.java:3041)
05-23 10:11:28.187 19171 19171 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:3024)
05-23 10:11:28.187 19171 19171 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2966)
05-23 10:11:28.187 19171 19171 E AndroidRuntime: 	at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:5722)
05-23 10:11:28.187 19171 19171 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-23 10:11:28.187 19171 19171 E AndroidRuntime: 	at leakcanary.ServiceWatcher$install$4$2.invoke(ServiceWatcher.kt:93)
05-23 10:11:28.187 19171 19171 E AndroidRuntime: 	at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
05-23 10:11:28.187 19171 19171 E AndroidRuntime: 	at $Proxy4.registerReceiverWithFeature(Unknown Source)
05-23 10:11:28.187 19171 19171 E AndroidRuntime: 	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1865)
05-23 10:11:28.187 19171 19171 E AndroidRuntime: 	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1805)
05-23 10:11:28.187 19171 19171 E AndroidRuntime: 	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1793)
05-23 10:11:28.187 19171 19171 E AndroidRuntime: 	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:755)
05-23 10:11:28.187 19171 19171 E AndroidRuntime: 	at org.autojs.autojs.external.receiver.DynamicBroadcastReceivers.<init>(DynamicBroadcastReceivers.java:36)
05-23 10:11:28.187 19171 19171 E AndroidRuntime: 	at org.autojs.autojs.App.initDynamicBroadcastReceivers(App.kt:97)
05-23 10:11:28.187 19171 19171 E AndroidRuntime: 	at org.autojs.autojs.App.init(App.kt:91)
05-23 10:11:28.187 19171 19171 E AndroidRuntime: 	at org.autojs.autojs.App.onCreate(App.kt:52)
05-23 10:11:28.187 19171 19171 E AndroidRuntime: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1322)
05-23 10:11:28.187 19171 19171 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7148)
05-23 10:11:28.187 19171 19171 E AndroidRuntime: 	... 9 more
05-23 10:11:28.187 19171 19171 E CrashHandler: Uncaught Exception
05-23 10:11:28.187 19171 19171 E CrashHandler: java.lang.RuntimeException: Unable to create application org.autojs.autojs.App: java.lang.SecurityException: org.autojs.autoxjs.v6: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
05-23 10:11:28.187 19171 19171 E CrashHandler: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7153)
05-23 10:11:28.187 19171 19171 E CrashHandler: 	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
05-23 10:11:28.187 19171 19171 E CrashHandler: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2278)
05-23 10:11:28.187 19171 19171 E CrashHandler: 	at android.os.Handler.dispatchMessage(Handler.java:106)
05-23 10:11:28.187 19171 19171 E CrashHandler: 	at android.os.Looper.loopOnce(Looper.java:205)
05-23 10:11:28.187 19171 19171 E CrashHandler: 	at android.os.Looper.loop(Looper.java:294)
05-23 10:11:28.187 19171 19171 E CrashHandler: 	at android.app.ActivityThread.main(ActivityThread.java:8358)
05-23 10:11:28.187 19171 19171 E CrashHandler: 	at java.lang.reflect.Method.invoke(Native Method)
05-23 10:11:28.187 19171 19171 E CrashHandler: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
05-23 10:11:28.187 19171 19171 E CrashHandler: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:977)
05-23 10:11:28.187 19171 19171 E CrashHandler: Caused by: java.lang.SecurityException: org.autojs.autoxjs.v6: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
05-23 10:11:28.187 19171 19171 E CrashHandler: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
05-23 10:11:28.187 19171 19171 E CrashHandler: 	at android.os.Parcel.createException(Parcel.java:3041)
05-23 10:11:28.187 19171 19171 E CrashHandler: 	at android.os.Parcel.readException(Parcel.java:3024)
05-23 10:11:28.187 19171 19171 E CrashHandler: 	at android.os.Parcel.readException(Parcel.java:2966)
05-23 10:11:28.187 19171 19171 E CrashHandler: 	at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:5722)
05-23 10:11:28.187 19171 19171 E CrashHandler: 	at java.lang.reflect.Method.invoke(Native Method)
05-23 10:11:28.187 19171 19171 E CrashHandler: 	at leakcanary.ServiceWatcher$install$4$2.invoke(ServiceWatcher.kt:93)
05-23 10:11:28.187 19171 19171 E CrashHandler: 	at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
05-23 10:11:28.187 19171 19171 E CrashHandler: 	at $Proxy4.registerReceiverWithFeature(Unknown Source)
05-23 10:11:28.187 19171 19171 E CrashHandler: 	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1865)
05-23 10:11:28.187 19171 19171 E CrashHandler: 	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1805)
05-23 10:11:28.187 19171 19171 E CrashHandler: 	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1793)
05-23 10:11:28.187 19171 19171 E CrashHandler: 	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:755)
05-23 10:11:28.187 19171 19171 E CrashHandler: 	at org.autojs.autojs.external.receiver.DynamicBroadcastReceivers.<init>(DynamicBroadcastReceivers.java:36)
05-23 10:11:28.187 19171 19171 E CrashHandler: 	at org.autojs.autojs.App.initDynamicBroadcastReceivers(App.kt:97)
05-23 10:11:28.187 19171 19171 E CrashHandler: 	at org.autojs.autojs.App.init(App.kt:91)
05-23 10:11:28.187 19171 19171 E CrashHandler: 	at org.autojs.autojs.App.onCreate(App.kt:52)
05-23 10:11:28.187 19171 19171 E CrashHandler: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1322)
05-23 10:11:28.187 19171 19171 E CrashHandler: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7148)
05-23 10:11:28.187 19171 19171 E CrashHandler: 	... 9 more
05-23 10:11:28.206 19171 19230 I DpmTcmClient: RegisterTcmMonitor from: $Proxy2
05-23 10:11:28.215  2869  5087 I FlymeDisplayController: canStartInDisplay mDisplayId=0,hasFeature=false,hasStartPackage=false
05-23 10:11:28.215  2869  5087 I FlymeDisplayController: canStartInDisplay mDisplayId=0,hasFeature=false,hasStartPackage=false
05-23 10:11:28.216  2869  5087 I ActivityTaskManager: START u0 {flg=0x30000000 cmp=org.autojs.autoxjs.v6/org.autojs.autojs.ui.error.ErrorReportActivity (has extras)} with LAUNCH_MULTIPLE from uid 10236 (BAL_ALLOW_VISIBLE_WINDOW) result code=3
05-23 10:11:28.519  2869  3593 E TrafficController: getUidLocalPermissionAll with error: Failed to get next key of map:283
05-23 10:11:28.543 19171 19171 W System.err: java.lang.RuntimeException: Unable to create application org.autojs.autojs.App: java.lang.SecurityException: org.autojs.autoxjs.v6: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
05-23 10:11:28.543 19171 19171 W System.err: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7153)
05-23 10:11:28.543 19171 19171 W System.err: 	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
05-23 10:11:28.543 19171 19171 W System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2278)
05-23 10:11:28.543 19171 19171 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:106)
05-23 10:11:28.543 19171 19171 W System.err: 	at android.os.Looper.loopOnce(Looper.java:205)
05-23 10:11:28.543 19171 19171 W System.err: 	at android.os.Looper.loop(Looper.java:294)
05-23 10:11:28.543 19171 19171 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:8358)
05-23 10:11:28.543 19171 19171 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
05-23 10:11:28.543 19171 19171 W System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
05-23 10:11:28.543 19171 19171 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:977)
05-23 10:11:28.543 19171 19171 W System.err: Caused by: java.lang.SecurityException: org.autojs.autoxjs.v6: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
05-23 10:11:28.543 19171 19171 W System.err: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
05-23 10:11:28.543 19171 19171 W System.err: 	at android.os.Parcel.createException(Parcel.java:3041)
05-23 10:11:28.543 19171 19171 W System.err: 	at android.os.Parcel.readException(Parcel.java:3024)
05-23 10:11:28.543 19171 19171 W System.err: 	at android.os.Parcel.readException(Parcel.java:2966)
05-23 10:11:28.543 19171 19171 W System.err: 	at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:5722)
05-23 10:11:28.543 19171 19171 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
05-23 10:11:28.543 19171 19171 W System.err: 	at leakcanary.ServiceWatcher$install$4$2.invoke(ServiceWatcher.kt:93)
05-23 10:11:28.543 19171 19171 W System.err: 	at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
05-23 10:11:28.543 19171 19171 W System.err: 	at $Proxy4.registerReceiverWithFeature(Unknown Source)
05-23 10:11:28.543 19171 19171 W System.err: 	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1865)
05-23 10:11:28.543 19171 19171 W System.err: 	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1805)
05-23 10:11:28.543 19171 19171 W System.err: 	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1793)
05-23 10:11:28.543 19171 19171 W System.err: 	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:755)
05-23 10:11:28.543 19171 19171 W System.err: 	at org.autojs.autojs.external.receiver.DynamicBroadcastReceivers.<init>(DynamicBroadcastReceivers.java:36)
05-23 10:11:28.543 19171 19171 W System.err: 	at org.autojs.autojs.App.initDynamicBroadcastReceivers(App.kt:97)
05-23 10:11:28.543 19171 19171 W System.err: 	at org.autojs.autojs.App.init(App.kt:91)
05-23 10:11:28.543 19171 19171 W System.err: 	at org.autojs.autojs.App.onCreate(App.kt:52)
05-23 10:11:28.543 19171 19171 W System.err: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1322)
05-23 10:11:28.543 19171 19171 W System.err: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7148)
05-23 10:11:28.543 19171 19171 W System.err: 	... 9 more
05-23 10:11:28.561  1646 16082 I QC2Comp : [hevcD_111] Stats: Pending(3) i/p-done(3) Works: Q: 17/Done 15|Work-Rate: Q(0.0/s Avg=0.1/s) Done(0.000/s Avg=0.083/s)| Stream: 30.30fps 2.0Mbps
05-23 10:11:28.561  1646 16082 I QC2Comp : [hevcD_111] Mem-usage:  [In-1D: 4 bufs 17.578 MB] [1D-203: 14 bufs 0.219 MB] [2D-204: 22 bufs 31.281 MB] | Total: 49.078 MB

**Comment by vmaskday** [comment]
[logcat.txt](https://github.com/kkevsekk1/AutoX/files/15410648/logcat.txt)
报错日志文件
